package com.webify.shared.edi.model.hipaa271.beans;

import java.util.*;
import com.webify.shared.edi.model.*;

/*
 * AUTOGENERATED FILE - DO NOT EDIT!!!
 */
public class Field98 {

	private static final Object[] DEFAULT_LEGAL_VALUES = new Object[151];
	private static final Map valueOverrides = new HashMap();

	static {
		DEFAULT_LEGAL_VALUES[0] = new String[] { "01", "09" };
		DEFAULT_LEGAL_VALUES[1] = "0A";
		DEFAULT_LEGAL_VALUES[2] = "0B";
		DEFAULT_LEGAL_VALUES[3] = new String[] { "0D", "0F" };
		DEFAULT_LEGAL_VALUES[4] = "0H";
		DEFAULT_LEGAL_VALUES[5] = new String[] { "10", "19" };
		DEFAULT_LEGAL_VALUES[6] = new String[] { "1A", "1Z" };
		DEFAULT_LEGAL_VALUES[7] = new String[] { "20", "29" };
		DEFAULT_LEGAL_VALUES[8] = new String[] { "2A", "2Z" };
		DEFAULT_LEGAL_VALUES[9] = new String[] { "30", "39" };
		DEFAULT_LEGAL_VALUES[10] = new String[] { "3A", "3Z" };
		DEFAULT_LEGAL_VALUES[11] = new String[] { "40", "49" };
		DEFAULT_LEGAL_VALUES[12] = new String[] { "4A", "4Z" };
		DEFAULT_LEGAL_VALUES[13] = new String[] { "50", "59" };
		DEFAULT_LEGAL_VALUES[14] = new String[] { "5A", "5Z" };
		DEFAULT_LEGAL_VALUES[15] = new String[] { "60", "69" };
		DEFAULT_LEGAL_VALUES[16] = new String[] { "6A", "6Z" };
		DEFAULT_LEGAL_VALUES[17] = new String[] { "70", "79" };
		DEFAULT_LEGAL_VALUES[18] = new String[] { "7A", "7Z" };
		DEFAULT_LEGAL_VALUES[19] = new String[] { "80", "89" };
		DEFAULT_LEGAL_VALUES[20] = new String[] { "8A", "8Z" };
		DEFAULT_LEGAL_VALUES[21] = new String[] { "90", "99" };
		DEFAULT_LEGAL_VALUES[22] = new String[] { "9A", "9L" };
		DEFAULT_LEGAL_VALUES[23] = new String[] { "9N", "9Z" };
		DEFAULT_LEGAL_VALUES[24] = new String[] { "A1", "A9" };
		DEFAULT_LEGAL_VALUES[25] = new String[] { "AA", "AZ" };
		DEFAULT_LEGAL_VALUES[26] = new String[] { "B1", "B9" };
		DEFAULT_LEGAL_VALUES[27] = new String[] { "BA", "BZ" };
		DEFAULT_LEGAL_VALUES[28] = new String[] { "C1", "C9" };
		DEFAULT_LEGAL_VALUES[29] = new String[] { "CA", "CZ" };
		DEFAULT_LEGAL_VALUES[30] = new String[] { "D1", "D9" };
		DEFAULT_LEGAL_VALUES[31] = new String[] { "DA", "DZ" };
		DEFAULT_LEGAL_VALUES[32] = new String[] { "E1", "E9" };
		DEFAULT_LEGAL_VALUES[33] = new String[] { "EA", "EZ" };
		DEFAULT_LEGAL_VALUES[34] = new String[] { "F1", "F9" };
		DEFAULT_LEGAL_VALUES[35] = new String[] { "FA", "FJ" };
		DEFAULT_LEGAL_VALUES[36] = new String[] { "FL", "FZ" };
		DEFAULT_LEGAL_VALUES[37] = new String[] { "G0", "G3" };
		DEFAULT_LEGAL_VALUES[38] = new String[] { "G5", "G9" };
		DEFAULT_LEGAL_VALUES[39] = new String[] { "GA", "GZ" };
		DEFAULT_LEGAL_VALUES[40] = new String[] { "H1", "H3" };
		DEFAULT_LEGAL_VALUES[41] = new String[] { "H5", "H9" };
		DEFAULT_LEGAL_VALUES[42] = new String[] { "HA", "HZ" };
		DEFAULT_LEGAL_VALUES[43] = "I1";
		DEFAULT_LEGAL_VALUES[44] = "I3";
		DEFAULT_LEGAL_VALUES[45] = "I4";
		DEFAULT_LEGAL_VALUES[46] = "I9";
		DEFAULT_LEGAL_VALUES[47] = new String[] { "IA", "IF" };
		DEFAULT_LEGAL_VALUES[48] = new String[] { "II", "IV" };
		DEFAULT_LEGAL_VALUES[49] = new String[] { "J1", "J9" };
		DEFAULT_LEGAL_VALUES[50] = new String[] { "JA", "JZ" };
		DEFAULT_LEGAL_VALUES[51] = new String[] { "K1", "K9" };
		DEFAULT_LEGAL_VALUES[52] = new String[] { "KA", "KZ" };
		DEFAULT_LEGAL_VALUES[53] = new String[] { "L1", "L3" };
		DEFAULT_LEGAL_VALUES[54] = "L5";
		DEFAULT_LEGAL_VALUES[55] = "L8";
		DEFAULT_LEGAL_VALUES[56] = "L9";
		DEFAULT_LEGAL_VALUES[57] = new String[] { "LA", "LW" };
		DEFAULT_LEGAL_VALUES[58] = "LY";
		DEFAULT_LEGAL_VALUES[59] = "LZ";
		DEFAULT_LEGAL_VALUES[60] = new String[] { "M1", "M9" };
		DEFAULT_LEGAL_VALUES[61] = new String[] { "MA", "MZ" };
		DEFAULT_LEGAL_VALUES[62] = new String[] { "N1", "N9" };
		DEFAULT_LEGAL_VALUES[63] = new String[] { "NB", "NN" };
		DEFAULT_LEGAL_VALUES[64] = new String[] { "NP", "NZ" };
		DEFAULT_LEGAL_VALUES[65] = new String[] { "O1", "O8" };
		DEFAULT_LEGAL_VALUES[66] = new String[] { "OA", "OI" };
		DEFAULT_LEGAL_VALUES[67] = new String[] { "OK", "OP" };
		DEFAULT_LEGAL_VALUES[68] = new String[] { "OR", "OZ" };
		DEFAULT_LEGAL_VALUES[69] = new String[] { "P0", "P9" };
		DEFAULT_LEGAL_VALUES[70] = new String[] { "PA", "PZ" };
		DEFAULT_LEGAL_VALUES[71] = new String[] { "Q1", "Q9" };
		DEFAULT_LEGAL_VALUES[72] = new String[] { "QA", "QZ" };
		DEFAULT_LEGAL_VALUES[73] = new String[] { "R0", "R9" };
		DEFAULT_LEGAL_VALUES[74] = new String[] { "RA", "RZ" };
		DEFAULT_LEGAL_VALUES[75] = new String[] { "S0", "S9" };
		DEFAULT_LEGAL_VALUES[76] = new String[] { "SA", "SZ" };
		DEFAULT_LEGAL_VALUES[77] = new String[] { "T1", "T4" };
		DEFAULT_LEGAL_VALUES[78] = "T6";
		DEFAULT_LEGAL_VALUES[79] = "T8";
		DEFAULT_LEGAL_VALUES[80] = "T9";
		DEFAULT_LEGAL_VALUES[81] = new String[] { "TA", "TZ" };
		DEFAULT_LEGAL_VALUES[82] = new String[] { "U1", "U9" };
		DEFAULT_LEGAL_VALUES[83] = new String[] { "UA", "UU" };
		DEFAULT_LEGAL_VALUES[84] = new String[] { "UW", "UZ" };
		DEFAULT_LEGAL_VALUES[85] = new String[] { "V1", "V6" };
		DEFAULT_LEGAL_VALUES[86] = "V8";
		DEFAULT_LEGAL_VALUES[87] = "V9";
		DEFAULT_LEGAL_VALUES[88] = new String[] { "VA", "VZ" };
		DEFAULT_LEGAL_VALUES[89] = new String[] { "W1", "W4" };
		DEFAULT_LEGAL_VALUES[90] = "W8";
		DEFAULT_LEGAL_VALUES[91] = "W9";
		DEFAULT_LEGAL_VALUES[92] = new String[] { "WA", "WJ" };
		DEFAULT_LEGAL_VALUES[93] = "WL";
		DEFAULT_LEGAL_VALUES[94] = new String[] { "WN", "WP" };
		DEFAULT_LEGAL_VALUES[95] = new String[] { "WR", "WZ" };
		DEFAULT_LEGAL_VALUES[96] = new String[] { "X1", "X8" };
		DEFAULT_LEGAL_VALUES[97] = "XA";
		DEFAULT_LEGAL_VALUES[98] = new String[] { "XC", "XZ" };
		DEFAULT_LEGAL_VALUES[99] = "Y2";
		DEFAULT_LEGAL_VALUES[100] = new String[] { "YA", "YZ" };
		DEFAULT_LEGAL_VALUES[101] = new String[] { "Z1", "Z9" };
		DEFAULT_LEGAL_VALUES[102] = new String[] { "ZA", "ZH" };
		DEFAULT_LEGAL_VALUES[103] = new String[] { "ZJ", "ZZ" };
		DEFAULT_LEGAL_VALUES[104] = new String[] { "001", "007" };
		DEFAULT_LEGAL_VALUES[105] = new String[] { "AAA", "AAQ" };
		DEFAULT_LEGAL_VALUES[106] = new String[] { "AAS", "AAV" };
		DEFAULT_LEGAL_VALUES[107] = new String[] { "ABB", "ABM" };
		DEFAULT_LEGAL_VALUES[108] = "ALA";
		DEFAULT_LEGAL_VALUES[109] = "BAL";
		DEFAULT_LEGAL_VALUES[110] = "BKR";
		DEFAULT_LEGAL_VALUES[111] = "BRN";
		DEFAULT_LEGAL_VALUES[112] = "BUS";
		DEFAULT_LEGAL_VALUES[113] = "CMW";
		DEFAULT_LEGAL_VALUES[114] = "COL";
		DEFAULT_LEGAL_VALUES[115] = "COR";
		DEFAULT_LEGAL_VALUES[116] = "DCC";
		DEFAULT_LEGAL_VALUES[117] = "DIR";
		DEFAULT_LEGAL_VALUES[118] = "ENR";
		DEFAULT_LEGAL_VALUES[119] = "EXS";
		DEFAULT_LEGAL_VALUES[120] = "FRL";
		DEFAULT_LEGAL_VALUES[121] = "FSR";
		DEFAULT_LEGAL_VALUES[122] = "GIR";
		DEFAULT_LEGAL_VALUES[123] = "HMI";
		DEFAULT_LEGAL_VALUES[124] = "HOM";
		DEFAULT_LEGAL_VALUES[125] = "IAA";
		DEFAULT_LEGAL_VALUES[126] = new String[] { "IAC", "IAI" };
		DEFAULT_LEGAL_VALUES[127] = new String[] { "IAK", "IAW" };
		DEFAULT_LEGAL_VALUES[128] = "IAY";
		DEFAULT_LEGAL_VALUES[129] = "IAZ";
		DEFAULT_LEGAL_VALUES[130] = "INV";
		DEFAULT_LEGAL_VALUES[131] = "LGS";
		DEFAULT_LEGAL_VALUES[132] = new String[] { "LYM", "LYP" };
		DEFAULT_LEGAL_VALUES[133] = "MSC";
		DEFAULT_LEGAL_VALUES[134] = "NCT";
		DEFAULT_LEGAL_VALUES[135] = "NPC";
		DEFAULT_LEGAL_VALUES[136] = "ORI";
		DEFAULT_LEGAL_VALUES[137] = "PLR";
		DEFAULT_LEGAL_VALUES[138] = "PMF";
		DEFAULT_LEGAL_VALUES[139] = "PPS";
		DEFAULT_LEGAL_VALUES[140] = "PRE";
		DEFAULT_LEGAL_VALUES[141] = "PRP";
		DEFAULT_LEGAL_VALUES[142] = "PUR";
		DEFAULT_LEGAL_VALUES[143] = "RCR";
		DEFAULT_LEGAL_VALUES[144] = "REC";
		DEFAULT_LEGAL_VALUES[145] = "RGA";
		DEFAULT_LEGAL_VALUES[146] = "SEP";
		DEFAULT_LEGAL_VALUES[147] = "TPM";
		DEFAULT_LEGAL_VALUES[148] = "TSE";
		DEFAULT_LEGAL_VALUES[149] = "TSR";
		DEFAULT_LEGAL_VALUES[150] = "TTP";
		createOverrides();
	}

	public static Object[] getLegalValues(String overrideKey) {
		Object[] currentValues = (Object[]) valueOverrides.get(overrideKey);
		if (currentValues == null) {
			return DEFAULT_LEGAL_VALUES;
		}
		return currentValues;
	}

	private static void createOverrides() {
		Object[] currentValues = null;

		currentValues = new Object[1];
		currentValues[0] = "03";
		valueOverrides.put("40-1", currentValues);

		currentValues = new Object[8];
		currentValues[0] = "1P";
		currentValues[1] = "2B";
		currentValues[2] = "36";
		currentValues[3] = "80";
		currentValues[4] = "FA";
		currentValues[5] = "GP";
		currentValues[6] = "P5";
		currentValues[7] = "PR";
		valueOverrides.put("10-1", currentValues);

		currentValues = new Object[16];
		currentValues[0] = "13";
		currentValues[1] = "1P";
		currentValues[2] = "2B";
		currentValues[3] = "36";
		currentValues[4] = "73";
		currentValues[5] = "FA";
		currentValues[6] = "GP";
		currentValues[7] = "IL";
		currentValues[8] = "LR";
		currentValues[9] = new String[] { "P3", "P5" };
		currentValues[10] = "PR";
		currentValues[11] = "VN";
		currentValues[12] = "X3";
		currentValues[13] = "PRP";
		currentValues[14] = "SEP";
		currentValues[15] = "TTP";
		valueOverrides.put("32-1", currentValues);

		currentValues = new Object[16];
		currentValues[0] = "13";
		currentValues[1] = "1P";
		currentValues[2] = "2B";
		currentValues[3] = "36";
		currentValues[4] = "73";
		currentValues[5] = "FA";
		currentValues[6] = "GP";
		currentValues[7] = "IL";
		currentValues[8] = "LR";
		currentValues[9] = new String[] { "P3", "P5" };
		currentValues[10] = "PR";
		currentValues[11] = "VN";
		currentValues[12] = "X3";
		currentValues[13] = "PRP";
		currentValues[14] = "SEP";
		currentValues[15] = "TTP";
		valueOverrides.put("57-1", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "IL";
		valueOverrides.put("15-1", currentValues);

		currentValues = new Object[5];
		currentValues[0] = "2B";
		currentValues[1] = "36";
		currentValues[2] = "GP";
		currentValues[3] = "P5";
		currentValues[4] = "PR";
		valueOverrides.put("5-1", currentValues);
	}

	public static boolean validateValue(String value) {
		return EDIUtils.validateValue(value, DEFAULT_LEGAL_VALUES);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, int segmentOrdinal, int fieldOrdinal) {
		String overrideKey = segmentOrdinal + "-" + fieldOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, String compositeOrdinal, int elementOrdinal) {
		String overrideKey = compositeOrdinal + "-" + elementOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}
}
