package com.webify.shared.edi.model.hipaa271.beans;

import java.util.*;
import com.webify.shared.edi.model.*;

/*
 * AUTOGENERATED FILE - DO NOT EDIT!!!
 */
public class Field1068 {

	private static final Object[] DEFAULT_LEGAL_VALUES = new Object[7];
	private static final Map valueOverrides = new HashMap();

	static {
		DEFAULT_LEGAL_VALUES[0] = "A";
		DEFAULT_LEGAL_VALUES[1] = "B";
		DEFAULT_LEGAL_VALUES[2] = "F";
		DEFAULT_LEGAL_VALUES[3] = "M";
		DEFAULT_LEGAL_VALUES[4] = "N";
		DEFAULT_LEGAL_VALUES[5] = "U";
		DEFAULT_LEGAL_VALUES[6] = "X";
		createOverrides();
	}

	public static Object[] getLegalValues(String overrideKey) {
		Object[] currentValues = (Object[]) valueOverrides.get(overrideKey);
		if (currentValues == null) {
			return DEFAULT_LEGAL_VALUES;
		}
		return currentValues;
	}

	private static void createOverrides() {
		Object[] currentValues = null;

		currentValues = new Object[3];
		currentValues[0] = "F";
		currentValues[1] = "M";
		currentValues[2] = "U";
		valueOverrides.put("21-3", currentValues);

		currentValues = new Object[3];
		currentValues[0] = "F";
		currentValues[1] = "M";
		currentValues[2] = "U";
		valueOverrides.put("46-3", currentValues);
	}

	public static boolean validateValue(String value) {
		return EDIUtils.validateValue(value, DEFAULT_LEGAL_VALUES);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, int segmentOrdinal, int fieldOrdinal) {
		String overrideKey = segmentOrdinal + "-" + fieldOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, String compositeOrdinal, int elementOrdinal) {
		String overrideKey = compositeOrdinal + "-" + elementOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}
}
