package com.webify.shared.edi.model.hipaa271.beans;

import java.util.*;
import com.webify.shared.edi.model.*;

/*
 * AUTOGENERATED FILE - DO NOT EDIT!!!
 */
public class Field889 {

	private static final Object[] DEFAULT_LEGAL_VALUES = new Object[6];
	private static final Map valueOverrides = new HashMap();

	static {
		DEFAULT_LEGAL_VALUES[0] = new String[] { "C", "E" };
		DEFAULT_LEGAL_VALUES[1] = "N";
		DEFAULT_LEGAL_VALUES[2] = "P";
		DEFAULT_LEGAL_VALUES[3] = "R";
		DEFAULT_LEGAL_VALUES[4] = "S";
		DEFAULT_LEGAL_VALUES[5] = new String[] { "W", "Y" };
		createOverrides();
	}

	public static Object[] getLegalValues(String overrideKey) {
		Object[] currentValues = (Object[]) valueOverrides.get(overrideKey);
		if (currentValues == null) {
			return DEFAULT_LEGAL_VALUES;
		}
		return currentValues;
	}

	private static void createOverrides() {
		Object[] currentValues = null;

		currentValues = new Object[6];
		currentValues[0] = "C";
		currentValues[1] = "N";
		currentValues[2] = "P";
		currentValues[3] = "R";
		currentValues[4] = "S";
		currentValues[5] = "Y";
		valueOverrides.put("4-4", currentValues);

		currentValues = new Object[4];
		currentValues[0] = "C";
		currentValues[1] = "N";
		currentValues[2] = "R";
		currentValues[3] = new String[] { "W", "Y" };
		valueOverrides.put("28-4", currentValues);

		currentValues = new Object[5];
		currentValues[0] = "C";
		currentValues[1] = "N";
		currentValues[2] = "R";
		currentValues[3] = "S";
		currentValues[4] = new String[] { "W", "Y" };
		valueOverrides.put("20-4", currentValues);

		currentValues = new Object[5];
		currentValues[0] = "C";
		currentValues[1] = "N";
		currentValues[2] = "R";
		currentValues[3] = "S";
		currentValues[4] = new String[] { "W", "Y" };
		valueOverrides.put("12-4", currentValues);

		currentValues = new Object[5];
		currentValues[0] = "C";
		currentValues[1] = "N";
		currentValues[2] = "R";
		currentValues[3] = "S";
		currentValues[4] = new String[] { "W", "Y" };
		valueOverrides.put("45-4", currentValues);

		currentValues = new Object[6];
		currentValues[0] = "C";
		currentValues[1] = "N";
		currentValues[2] = "P";
		currentValues[3] = "R";
		currentValues[4] = "S";
		currentValues[5] = new String[] { "W", "Y" };
		valueOverrides.put("8-4", currentValues);

		currentValues = new Object[4];
		currentValues[0] = "C";
		currentValues[1] = "N";
		currentValues[2] = "R";
		currentValues[3] = new String[] { "W", "Y" };
		valueOverrides.put("53-4", currentValues);
	}

	public static boolean validateValue(String value) {
		return EDIUtils.validateValue(value, DEFAULT_LEGAL_VALUES);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, int segmentOrdinal, int fieldOrdinal) {
		String overrideKey = segmentOrdinal + "-" + fieldOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, String compositeOrdinal, int elementOrdinal) {
		String overrideKey = compositeOrdinal + "-" + elementOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}
}
