package com.webify.shared.edi.model.hipaa271.beans;

import com.webify.shared.edi.model.*;
import java.io.*;
import java.util.*;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/*
 * AUTOGENERATED FILE - DO NOT EDIT!!!
 */
public class SegmentLS_1 implements EDIElement {
	private static final Log log = LogFactory.getLog(SegmentLS_1.class);

	public static final String SEGMENT_NAME = "LS";
	public static final int FIELD_COUNT = 1;

	private int lineNumber = 0;
	public int getLineNumber() { return lineNumber; }
	/** Do NOT use this method - it is not public by choice... */
	public void setLineNumber(int foo) { lineNumber = foo; }

	private int ordinal = 0;
	public int getOrdinal() { return ordinal; }
	void setOrdinal(int ord) { ordinal = ord; }

	// Fields
	private String Ls01;
	public String getLs01() { return Ls01; }
	public void setLs01(String val) { Ls01 = val; }


	public void parse(EDIInputStream eis) throws IOException {
		lineNumber = eis.getCurrentSegmentNumber();
		if (log.isDebugEnabled()) log.debug("Starting segment LS on line " + lineNumber);
		String[] fields = eis.readSegment(SEGMENT_NAME, FIELD_COUNT);
		Ls01 = eis.getStringValue(fields, 1, 1, 6, true);
		if (Ls01 == null || "".equals(fields[1].trim())) {
			eis.addError("Field 'LS01' missing");
		}
	}

	public void emit(EDIOutputStream eos) throws IOException {
		eos.startSegment("LS");
		if (Ls01 == null) {
			eos.addError("Emitting null mandatory field 'LS01'");
		}

		eos.writeField(Ls01);
		eos.endSegment();
	}

	public EDIElement createCopy() {
		SegmentLS_1 copy = new SegmentLS_1();
		copy.setLineNumber(this.lineNumber);
		copy.Ls01 = this.Ls01;
		return copy;
	}
}
