package com.webify.shared.edi.model.hipaa837i.beans;

import com.webify.shared.edi.model.*;
import com.webify.shared.edi.model.hipaa837i.*;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import java.io.IOException;
import java.util.*;

/*
 * AUTOGENERATED FILE - DO NOT EDIT!!!
 */
public class BaseLoop2010BA extends EDILoop {

	private static final Log log = LogFactory.getLog(Loop2010BA.class);

	private int startLineNumber, endLineNumber;
	public int getStartLineNumber() { return startLineNumber; }
	public int getEndLineNumber() { return endLineNumber; }

	/** Do NOT use this method - it is not public by choice... */
	public void setEndLineNumber(int foo) { endLineNumber = foo; }
	/** Do NOT use this method - it is not public by choice... */
	public void setStartLineNumber(int foo) { startLineNumber = foo; }

	public static final String[] TRIGGER_VALUES = new String[] {
		"IL"
	};

	// Segments
	private SegmentNM1_3 Nm1;
	public SegmentNM1_3 getNm1() { return Nm1; }
	public void setNm1(SegmentNM1_3 seg) { Nm1 = seg; }

	private SegmentN3_1 N3;
	public SegmentN3_1 getN3() { return N3; }
	public void setN3(SegmentN3_1 seg) { N3 = seg; }

	private SegmentN4_1 N4;
	public SegmentN4_1 getN4() { return N4; }
	public void setN4(SegmentN4_1 seg) { N4 = seg; }

	private SegmentDMG_1 Dmg;
	public SegmentDMG_1 getDmg() { return Dmg; }
	public void setDmg(SegmentDMG_1 seg) { Dmg = seg; }

	private List Ref01;
	public SegmentREF_1 getRef01(int idx) { 
		if (Ref01 == null || idx >= Ref01.size()) {
			throw new ArrayIndexOutOfBoundsException("Ref01");
		}
		return (SegmentREF_1) Ref01.get(idx);
	}
	public List getRef01() {
		return Ref01;
	}
	public void setRef01(List segs) { Ref01 = segs; }

	private SegmentREF_1 Ref02;
	public SegmentREF_1 getRef02() { return Ref02; }
	public void setRef02(SegmentREF_1 seg) { Ref02 = seg; }


	// Loops

	public void parse(EDIInputStream eis) throws IOException {
		if (log.isDebugEnabled()) log.debug("Starting loop 2010BA");
		startLineNumber = eis.getCurrentSegmentNumber() + 1;

		if (!eis.peekSegment("NM1")) {
			eis.addError("A single instance of Segment NM1 is required.");
		} else {
			Nm1 = new SegmentNM1_3();
			Nm1.setOrdinal(23);
			Nm1.parse(eis);
		}

		if (eis.peekSegment("N3")) {
			N3 = new SegmentN3_1();
			N3.setOrdinal(24);
			N3.parse(eis);
		}

		if (eis.peekSegment("N4")) {
			N4 = new SegmentN4_1();
			N4.setOrdinal(25);
			N4.parse(eis);
		}

		if (eis.peekSegment("DMG")) {
			Dmg = new SegmentDMG_1();
			Dmg.setOrdinal(26);
			Dmg.parse(eis);
		}

		while (eis.peekSegment("REF", 1, new String[] { "1W", "23", "IG", "SY" })) {
			if (Ref01 == null) Ref01 = new ArrayList();
			SegmentREF_1 tmp = new SegmentREF_1();
			tmp.setOrdinal(27);
			tmp.parse(eis);
			Ref01.add(tmp);
			if (Ref01.size() > 4) {
				eis.addError("Segment REF has too many instances.  It can only repeat 4 times");
				eis.eatSegments("REF");
				break;
			}
		}

		if (eis.peekSegment("REF", 1, "Y4")) {
			Ref02 = new SegmentREF_1();
			Ref02.setOrdinal(28);
			Ref02.parse(eis);
		}

		endLineNumber = eis.getCurrentSegmentNumber();
		validate(eis);
	}

	public void emit(EDIOutputStream eos) throws IOException {
		if (Nm1 != null) {
			Nm1.emit(eos);
		} else {
			eos.addError("Missing mandatory segment 'NM1'");
		}

		if (N3 != null) {
			N3.emit(eos);
		}

		if (N4 != null) {
			N4.emit(eos);
		}

		if (Dmg != null) {
			Dmg.emit(eos);
		}

		if (Ref01 != null) {
			int idx = 0, size = Ref01.size();
			while (idx < size) {
				getRef01(idx++).emit(eos);
			}
		}

		if (Ref02 != null) {
			Ref02.emit(eos);
		}

	}

	public EDIElement createCopy() {
		Loop2010BA thisCopy = new Loop2010BA();
		thisCopy.setStartLineNumber(this.startLineNumber);
		thisCopy.setEndLineNumber(this.endLineNumber);

		if (Nm1 != null) {
			thisCopy.setNm1((SegmentNM1_3)Nm1.createCopy());
		}

		if (N3 != null) {
			thisCopy.setN3((SegmentN3_1)N3.createCopy());
		}

		if (N4 != null) {
			thisCopy.setN4((SegmentN4_1)N4.createCopy());
		}

		if (Dmg != null) {
			thisCopy.setDmg((SegmentDMG_1)Dmg.createCopy());
		}

		if (Ref01 != null) {
			thisCopy.setRef01(new ArrayList());
			int idx = 0, size = Ref01.size();
			while (idx < size) {
				thisCopy.getRef01().add(getRef01(idx++).createCopy());
			}
		}

		if (Ref02 != null) {
			thisCopy.setRef02((SegmentREF_1)Ref02.createCopy());
		}

		return thisCopy;
	}

}
