package com.webify.shared.edi.model.hipaa837i.beans;

import java.util.*;
import com.webify.shared.edi.model.*;

/*
 * AUTOGENERATED FILE - DO NOT EDIT!!!
 */
public class Field363 {

	private static final Object[] DEFAULT_LEGAL_VALUES = new Object[198];
	private static final Map valueOverrides = new HashMap();

	static {
		DEFAULT_LEGAL_VALUES[0] = new String[] { "AAA", "AAF" };
		DEFAULT_LEGAL_VALUES[1] = "ABN";
		DEFAULT_LEGAL_VALUES[2] = "ACC";
		DEFAULT_LEGAL_VALUES[3] = "ACI";
		DEFAULT_LEGAL_VALUES[4] = "ACN";
		DEFAULT_LEGAL_VALUES[5] = "ACS";
		DEFAULT_LEGAL_VALUES[6] = "ACT";
		DEFAULT_LEGAL_VALUES[7] = "ADD";
		DEFAULT_LEGAL_VALUES[8] = "AES";
		DEFAULT_LEGAL_VALUES[9] = "AET";
		DEFAULT_LEGAL_VALUES[10] = "ALG";
		DEFAULT_LEGAL_VALUES[11] = "ALL";
		DEFAULT_LEGAL_VALUES[12] = "ALT";
		DEFAULT_LEGAL_VALUES[13] = "AMN";
		DEFAULT_LEGAL_VALUES[14] = "AOO";
		DEFAULT_LEGAL_VALUES[15] = "APN";
		DEFAULT_LEGAL_VALUES[16] = "APS";
		DEFAULT_LEGAL_VALUES[17] = "BBD";
		DEFAULT_LEGAL_VALUES[18] = "BBF";
		DEFAULT_LEGAL_VALUES[19] = "BBH";
		DEFAULT_LEGAL_VALUES[20] = "BBN";
		DEFAULT_LEGAL_VALUES[21] = "BBO";
		DEFAULT_LEGAL_VALUES[22] = "BBT";
		DEFAULT_LEGAL_VALUES[23] = "BFD";
		DEFAULT_LEGAL_VALUES[24] = "BOL";
		DEFAULT_LEGAL_VALUES[25] = "BUR";
		DEFAULT_LEGAL_VALUES[26] = new String[] { "CAA", "CAX" };
		DEFAULT_LEGAL_VALUES[27] = new String[] { "CAZ", "CBC" };
		DEFAULT_LEGAL_VALUES[28] = "CBH";
		DEFAULT_LEGAL_VALUES[29] = "CBI";
		DEFAULT_LEGAL_VALUES[30] = new String[] { "CCA", "CCG" };
		DEFAULT_LEGAL_VALUES[31] = "CCN";
		DEFAULT_LEGAL_VALUES[32] = "CDD";
		DEFAULT_LEGAL_VALUES[33] = "CER";
		DEFAULT_LEGAL_VALUES[34] = "CHG";
		DEFAULT_LEGAL_VALUES[35] = "CIG";
		DEFAULT_LEGAL_VALUES[36] = "CLN";
		DEFAULT_LEGAL_VALUES[37] = "CLR";
		DEFAULT_LEGAL_VALUES[38] = "CMP";
		DEFAULT_LEGAL_VALUES[39] = "CMT";
		DEFAULT_LEGAL_VALUES[40] = "COD";
		DEFAULT_LEGAL_VALUES[41] = "COM";
		DEFAULT_LEGAL_VALUES[42] = "CON";
		DEFAULT_LEGAL_VALUES[43] = "CRA";
		DEFAULT_LEGAL_VALUES[44] = "CRK";
		DEFAULT_LEGAL_VALUES[45] = "CRN";
		DEFAULT_LEGAL_VALUES[46] = "CUS";
		DEFAULT_LEGAL_VALUES[47] = "DCP";
		DEFAULT_LEGAL_VALUES[48] = "DEE";
		DEFAULT_LEGAL_VALUES[49] = "DEL";
		DEFAULT_LEGAL_VALUES[50] = "DEP";
		DEFAULT_LEGAL_VALUES[51] = "DFR";
		DEFAULT_LEGAL_VALUES[52] = "DFS";
		DEFAULT_LEGAL_VALUES[53] = "DGN";
		DEFAULT_LEGAL_VALUES[54] = "DME";
		DEFAULT_LEGAL_VALUES[55] = "DOD";
		DEFAULT_LEGAL_VALUES[56] = "DOI";
		DEFAULT_LEGAL_VALUES[57] = "ECD";
		DEFAULT_LEGAL_VALUES[58] = "ECM";
		DEFAULT_LEGAL_VALUES[59] = "ECN";
		DEFAULT_LEGAL_VALUES[60] = "ECT";
		DEFAULT_LEGAL_VALUES[61] = "EED";
		DEFAULT_LEGAL_VALUES[62] = "EFD";
		DEFAULT_LEGAL_VALUES[63] = "ELE";
		DEFAULT_LEGAL_VALUES[64] = "EMC";
		DEFAULT_LEGAL_VALUES[65] = "EMD";
		DEFAULT_LEGAL_VALUES[66] = "ENR";
		DEFAULT_LEGAL_VALUES[67] = "ERN";
		DEFAULT_LEGAL_VALUES[68] = "EVL";
		DEFAULT_LEGAL_VALUES[69] = "EXE";
		DEFAULT_LEGAL_VALUES[70] = "EXR";
		DEFAULT_LEGAL_VALUES[71] = "EXT";
		DEFAULT_LEGAL_VALUES[72] = "FEE";
		DEFAULT_LEGAL_VALUES[73] = "FUT";
		DEFAULT_LEGAL_VALUES[74] = "GEN";
		DEFAULT_LEGAL_VALUES[75] = "GPI";
		DEFAULT_LEGAL_VALUES[76] = "GSI";
		DEFAULT_LEGAL_VALUES[77] = "HHI";
		DEFAULT_LEGAL_VALUES[78] = "ICN";
		DEFAULT_LEGAL_VALUES[79] = "IDT";
		DEFAULT_LEGAL_VALUES[80] = "IID";
		DEFAULT_LEGAL_VALUES[81] = "IIE";
		DEFAULT_LEGAL_VALUES[82] = "IIR";
		DEFAULT_LEGAL_VALUES[83] = "IMP";
		DEFAULT_LEGAL_VALUES[84] = "INS";
		DEFAULT_LEGAL_VALUES[85] = "INT";
		DEFAULT_LEGAL_VALUES[86] = "INV";
		DEFAULT_LEGAL_VALUES[87] = "IVC";
		DEFAULT_LEGAL_VALUES[88] = "JVD";
		DEFAULT_LEGAL_VALUES[89] = "LAB";
		DEFAULT_LEGAL_VALUES[90] = "LBD";
		DEFAULT_LEGAL_VALUES[91] = "LBS";
		DEFAULT_LEGAL_VALUES[92] = "LEN";
		DEFAULT_LEGAL_VALUES[93] = "LIN";
		DEFAULT_LEGAL_VALUES[94] = "LIQ";
		DEFAULT_LEGAL_VALUES[95] = new String[] { "LLA", "LLC" };
		DEFAULT_LEGAL_VALUES[96] = "LOC";
		DEFAULT_LEGAL_VALUES[97] = "LOI";
		DEFAULT_LEGAL_VALUES[98] = "LSD";
		DEFAULT_LEGAL_VALUES[99] = "MCD";
		DEFAULT_LEGAL_VALUES[100] = "MDO";
		DEFAULT_LEGAL_VALUES[101] = "MED";
		DEFAULT_LEGAL_VALUES[102] = "MFG";
		DEFAULT_LEGAL_VALUES[103] = "MKN";
		DEFAULT_LEGAL_VALUES[104] = "MMD";
		DEFAULT_LEGAL_VALUES[105] = "MSD";
		DEFAULT_LEGAL_VALUES[106] = "NCD";
		DEFAULT_LEGAL_VALUES[107] = "NPD";
		DEFAULT_LEGAL_VALUES[108] = "NTR";
		DEFAULT_LEGAL_VALUES[109] = "OBI";
		DEFAULT_LEGAL_VALUES[110] = "OBL";
		DEFAULT_LEGAL_VALUES[111] = "OCA";
		DEFAULT_LEGAL_VALUES[112] = "OCC";
		DEFAULT_LEGAL_VALUES[113] = "OCL";
		DEFAULT_LEGAL_VALUES[114] = "OCP";
		DEFAULT_LEGAL_VALUES[115] = "OCR";
		DEFAULT_LEGAL_VALUES[116] = "ODT";
		DEFAULT_LEGAL_VALUES[117] = "OLS";
		DEFAULT_LEGAL_VALUES[118] = "OPO";
		DEFAULT_LEGAL_VALUES[119] = "ORA";
		DEFAULT_LEGAL_VALUES[120] = "ORE";
		DEFAULT_LEGAL_VALUES[121] = "ORI";
		DEFAULT_LEGAL_VALUES[122] = "OTH";
		DEFAULT_LEGAL_VALUES[123] = "OTN";
		DEFAULT_LEGAL_VALUES[124] = "OTS";
		DEFAULT_LEGAL_VALUES[125] = "PAY";
		DEFAULT_LEGAL_VALUES[126] = "PCS";
		DEFAULT_LEGAL_VALUES[127] = "PDS";
		DEFAULT_LEGAL_VALUES[128] = "PED";
		DEFAULT_LEGAL_VALUES[129] = "PEN";
		DEFAULT_LEGAL_VALUES[130] = "PES";
		DEFAULT_LEGAL_VALUES[131] = "PID";
		DEFAULT_LEGAL_VALUES[132] = "PKG";
		DEFAULT_LEGAL_VALUES[133] = "PMT";
		DEFAULT_LEGAL_VALUES[134] = "POB";
		DEFAULT_LEGAL_VALUES[135] = "POC";
		DEFAULT_LEGAL_VALUES[136] = "POL";
		DEFAULT_LEGAL_VALUES[137] = "PPC";
		DEFAULT_LEGAL_VALUES[138] = "PRI";
		DEFAULT_LEGAL_VALUES[139] = "PRN";
		DEFAULT_LEGAL_VALUES[140] = "PRO";
		DEFAULT_LEGAL_VALUES[141] = "PRR";
		DEFAULT_LEGAL_VALUES[142] = "PSY";
		DEFAULT_LEGAL_VALUES[143] = "PUR";
		DEFAULT_LEGAL_VALUES[144] = "QUL";
		DEFAULT_LEGAL_VALUES[145] = "QUT";
		DEFAULT_LEGAL_VALUES[146] = "RDI";
		DEFAULT_LEGAL_VALUES[147] = "REC";
		DEFAULT_LEGAL_VALUES[148] = "REG";
		DEFAULT_LEGAL_VALUES[149] = "REP";
		DEFAULT_LEGAL_VALUES[150] = "REV";
		DEFAULT_LEGAL_VALUES[151] = "RFL";
		DEFAULT_LEGAL_VALUES[152] = "RHB";
		DEFAULT_LEGAL_VALUES[153] = "RLA";
		DEFAULT_LEGAL_VALUES[154] = "RLH";
		DEFAULT_LEGAL_VALUES[155] = "RNH";
		DEFAULT_LEGAL_VALUES[156] = "RNI";
		DEFAULT_LEGAL_VALUES[157] = "ROU";
		DEFAULT_LEGAL_VALUES[158] = "RPT";
		DEFAULT_LEGAL_VALUES[159] = "RST";
		DEFAULT_LEGAL_VALUES[160] = "RVC";
		DEFAULT_LEGAL_VALUES[161] = "SAN";
		DEFAULT_LEGAL_VALUES[162] = "SCN";
		DEFAULT_LEGAL_VALUES[163] = "SDD";
		DEFAULT_LEGAL_VALUES[164] = "SET";
		DEFAULT_LEGAL_VALUES[165] = "SFM";
		DEFAULT_LEGAL_VALUES[166] = "SMD";
		DEFAULT_LEGAL_VALUES[167] = "SOB";
		DEFAULT_LEGAL_VALUES[168] = "SOW";
		DEFAULT_LEGAL_VALUES[169] = "SPH";
		DEFAULT_LEGAL_VALUES[170] = "SPT";
		DEFAULT_LEGAL_VALUES[171] = "SPV";
		DEFAULT_LEGAL_VALUES[172] = "SSA";
		DEFAULT_LEGAL_VALUES[173] = new String[] { "SSC", "SSE" };
		DEFAULT_LEGAL_VALUES[174] = new String[] { "SSG", "SSI" };
		DEFAULT_LEGAL_VALUES[175] = "SSS";
		DEFAULT_LEGAL_VALUES[176] = "SST";
		DEFAULT_LEGAL_VALUES[177] = "TAF";
		DEFAULT_LEGAL_VALUES[178] = "TCF";
		DEFAULT_LEGAL_VALUES[179] = "TDA";
		DEFAULT_LEGAL_VALUES[180] = "TES";
		DEFAULT_LEGAL_VALUES[181] = "TIL";
		DEFAULT_LEGAL_VALUES[182] = "TLF";
		DEFAULT_LEGAL_VALUES[183] = "TLR";
		DEFAULT_LEGAL_VALUES[184] = "TPO";
		DEFAULT_LEGAL_VALUES[185] = "TRA";
		DEFAULT_LEGAL_VALUES[186] = "TRE";
		DEFAULT_LEGAL_VALUES[187] = "TRF";
		DEFAULT_LEGAL_VALUES[188] = "TRS";
		DEFAULT_LEGAL_VALUES[189] = "TSD";
		DEFAULT_LEGAL_VALUES[190] = "TSF";
		DEFAULT_LEGAL_VALUES[191] = "TST";
		DEFAULT_LEGAL_VALUES[192] = "UPI";
		DEFAULT_LEGAL_VALUES[193] = "VEC";
		DEFAULT_LEGAL_VALUES[194] = "VNN";
		DEFAULT_LEGAL_VALUES[195] = "WHI";
		DEFAULT_LEGAL_VALUES[196] = "WRP";
		DEFAULT_LEGAL_VALUES[197] = "ZZZ";
		createOverrides();
	}

	public static Object[] getLegalValues(String overrideKey) {
		Object[] currentValues = (Object[]) valueOverrides.get(overrideKey);
		if (currentValues == null) {
			return DEFAULT_LEGAL_VALUES;
		}
		return currentValues;
	}

	private static void createOverrides() {
		Object[] currentValues = null;

		currentValues = new Object[14];
		currentValues[0] = "ALG";
		currentValues[1] = "DCP";
		currentValues[2] = "DGN";
		currentValues[3] = "DME";
		currentValues[4] = "MED";
		currentValues[5] = "NTR";
		currentValues[6] = "ODT";
		currentValues[7] = "RHB";
		currentValues[8] = "RLH";
		currentValues[9] = "RNH";
		currentValues[10] = "SET";
		currentValues[11] = "SFM";
		currentValues[12] = "SPT";
		currentValues[13] = "UPI";
		valueOverrides.put("191-1", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "ADD";
		valueOverrides.put("62-1", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "ADD";
		valueOverrides.put("192-1", currentValues);

		currentValues = new Object[14];
		currentValues[0] = "ALG";
		currentValues[1] = "DCP";
		currentValues[2] = "DGN";
		currentValues[3] = "DME";
		currentValues[4] = "MED";
		currentValues[5] = "NTR";
		currentValues[6] = "ODT";
		currentValues[7] = "RHB";
		currentValues[8] = "RLH";
		currentValues[9] = "RNH";
		currentValues[10] = "SET";
		currentValues[11] = "SFM";
		currentValues[12] = "SPT";
		currentValues[13] = "UPI";
		valueOverrides.put("61-1", currentValues);
	}

	public static boolean validateValue(String value) {
		return EDIUtils.validateValue(value, DEFAULT_LEGAL_VALUES);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, int segmentOrdinal, int fieldOrdinal) {
		String overrideKey = segmentOrdinal + "-" + fieldOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, String compositeOrdinal, int elementOrdinal) {
		String overrideKey = compositeOrdinal + "-" + elementOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}
}
