package com.webify.shared.edi.model.hipaa837i.beans;

import com.webify.shared.edi.model.*;
import java.io.*;
import java.util.*;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/*
 * AUTOGENERATED FILE - DO NOT EDIT!!!
 */
public class SegmentLX_1 implements EDIElement {
	private static final Log log = LogFactory.getLog(SegmentLX_1.class);

	public static final String SEGMENT_NAME = "LX";
	public static final int FIELD_COUNT = 1;

	private int lineNumber = 0;
	public int getLineNumber() { return lineNumber; }
	/** Do NOT use this method - it is not public by choice... */
	public void setLineNumber(int foo) { lineNumber = foo; }

	private int ordinal = 0;
	public int getOrdinal() { return ordinal; }
	void setOrdinal(int ord) { ordinal = ord; }

	// Fields
	private Integer Lx01;
	public Integer getLx01() { return Lx01; }
	public void setLx01(Integer val) { Lx01 = val; }


	public void parse(EDIInputStream eis) throws IOException {
		lineNumber = eis.getCurrentSegmentNumber();
		if (log.isDebugEnabled()) log.debug("Starting segment LX on line " + lineNumber);
		String[] fields = eis.readSegment(SEGMENT_NAME, FIELD_COUNT);
		Lx01 = eis.getIntegerValue(fields, 1, true);
		if (Lx01 == null || "".equals(fields[1].trim())) {
			eis.addError("Field 'LX01' missing");
		}
	}

	public void emit(EDIOutputStream eos) throws IOException {
		eos.startSegment("LX");
		if (Lx01 == null) {
			eos.addError("Emitting null mandatory field 'LX01'");
		}

		eos.writeField(Lx01);
		eos.endSegment();
	}

	public EDIElement createCopy() {
		SegmentLX_1 copy = new SegmentLX_1();
		copy.setLineNumber(this.lineNumber);
		copy.Lx01 = this.Lx01;
		return copy;
	}
}
