package com.webify.shared.edi.model.hipaa837i.beans;

import com.webify.shared.edi.model.*;
import java.io.*;
import java.util.*;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/*
 * AUTOGENERATED FILE - DO NOT EDIT!!!
 */
public class SegmentK3_1 implements EDIElement {
	private static final Log log = LogFactory.getLog(SegmentK3_1.class);

	public static final String SEGMENT_NAME = "K3";
	public static final int FIELD_COUNT = 1;

	private int lineNumber = 0;
	public int getLineNumber() { return lineNumber; }
	/** Do NOT use this method - it is not public by choice... */
	public void setLineNumber(int foo) { lineNumber = foo; }

	private int ordinal = 0;
	public int getOrdinal() { return ordinal; }
	void setOrdinal(int ord) { ordinal = ord; }

	// Fields
	private String K301;
	public String getK301() { return K301; }
	public void setK301(String val) { K301 = val; }


	public void parse(EDIInputStream eis) throws IOException {
		lineNumber = eis.getCurrentSegmentNumber();
		if (log.isDebugEnabled()) log.debug("Starting segment K3 on line " + lineNumber);
		String[] fields = eis.readSegment(SEGMENT_NAME, FIELD_COUNT);
		K301 = eis.getStringValue(fields, 1, 1, 80, true);
		if (K301 == null || "".equals(fields[1].trim())) {
			eis.addError("Field 'K301' missing");
		}
	}

	public void emit(EDIOutputStream eos) throws IOException {
		eos.startSegment("K3");
		if (K301 == null) {
			eos.addError("Emitting null mandatory field 'K301'");
		}

		eos.writeField(K301);
		eos.writeNullField();
		eos.writeNullField();
		eos.endSegment();
	}

	public EDIElement createCopy() {
		SegmentK3_1 copy = new SegmentK3_1();
		copy.setLineNumber(this.lineNumber);
		copy.K301 = this.K301;
		return copy;
	}
}
