package com.webify.shared.edi.model.hipaa837i.beans;

import com.webify.shared.edi.model.*;
import java.io.*;
import java.util.*;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/*
 * AUTOGENERATED FILE - DO NOT EDIT!!!
 */
public class SegmentMIA_1 implements EDIElement {
	private static final Log log = LogFactory.getLog(SegmentMIA_1.class);

	public static final String SEGMENT_NAME = "MIA";
	public static final int FIELD_COUNT = 24;

	private int lineNumber = 0;
	public int getLineNumber() { return lineNumber; }
	/** Do NOT use this method - it is not public by choice... */
	public void setLineNumber(int foo) { lineNumber = foo; }

	private int ordinal = 0;
	public int getOrdinal() { return ordinal; }
	void setOrdinal(int ord) { ordinal = ord; }

	// Fields
	private java.math.BigDecimal Mia01;
	public java.math.BigDecimal getMia01() { return Mia01; }
	public void setMia01(java.math.BigDecimal val) { Mia01 = val; }

	private java.math.BigDecimal Mia02;
	public java.math.BigDecimal getMia02() { return Mia02; }
	public void setMia02(java.math.BigDecimal val) { Mia02 = val; }

	private java.math.BigDecimal Mia03;
	public java.math.BigDecimal getMia03() { return Mia03; }
	public void setMia03(java.math.BigDecimal val) { Mia03 = val; }

	private java.math.BigDecimal Mia04;
	public java.math.BigDecimal getMia04() { return Mia04; }
	public void setMia04(java.math.BigDecimal val) { Mia04 = val; }

	private String Mia05;
	public String getMia05() { return Mia05; }
	public void setMia05(String val) { Mia05 = val; }

	private java.math.BigDecimal Mia06;
	public java.math.BigDecimal getMia06() { return Mia06; }
	public void setMia06(java.math.BigDecimal val) { Mia06 = val; }

	private java.math.BigDecimal Mia07;
	public java.math.BigDecimal getMia07() { return Mia07; }
	public void setMia07(java.math.BigDecimal val) { Mia07 = val; }

	private java.math.BigDecimal Mia08;
	public java.math.BigDecimal getMia08() { return Mia08; }
	public void setMia08(java.math.BigDecimal val) { Mia08 = val; }

	private java.math.BigDecimal Mia09;
	public java.math.BigDecimal getMia09() { return Mia09; }
	public void setMia09(java.math.BigDecimal val) { Mia09 = val; }

	private java.math.BigDecimal Mia10;
	public java.math.BigDecimal getMia10() { return Mia10; }
	public void setMia10(java.math.BigDecimal val) { Mia10 = val; }

	private java.math.BigDecimal Mia11;
	public java.math.BigDecimal getMia11() { return Mia11; }
	public void setMia11(java.math.BigDecimal val) { Mia11 = val; }

	private java.math.BigDecimal Mia12;
	public java.math.BigDecimal getMia12() { return Mia12; }
	public void setMia12(java.math.BigDecimal val) { Mia12 = val; }

	private java.math.BigDecimal Mia13;
	public java.math.BigDecimal getMia13() { return Mia13; }
	public void setMia13(java.math.BigDecimal val) { Mia13 = val; }

	private java.math.BigDecimal Mia14;
	public java.math.BigDecimal getMia14() { return Mia14; }
	public void setMia14(java.math.BigDecimal val) { Mia14 = val; }

	private java.math.BigDecimal Mia15;
	public java.math.BigDecimal getMia15() { return Mia15; }
	public void setMia15(java.math.BigDecimal val) { Mia15 = val; }

	private java.math.BigDecimal Mia16;
	public java.math.BigDecimal getMia16() { return Mia16; }
	public void setMia16(java.math.BigDecimal val) { Mia16 = val; }

	private java.math.BigDecimal Mia17;
	public java.math.BigDecimal getMia17() { return Mia17; }
	public void setMia17(java.math.BigDecimal val) { Mia17 = val; }

	private java.math.BigDecimal Mia18;
	public java.math.BigDecimal getMia18() { return Mia18; }
	public void setMia18(java.math.BigDecimal val) { Mia18 = val; }

	private java.math.BigDecimal Mia19;
	public java.math.BigDecimal getMia19() { return Mia19; }
	public void setMia19(java.math.BigDecimal val) { Mia19 = val; }

	private String Mia20;
	public String getMia20() { return Mia20; }
	public void setMia20(String val) { Mia20 = val; }

	private String Mia21;
	public String getMia21() { return Mia21; }
	public void setMia21(String val) { Mia21 = val; }

	private String Mia22;
	public String getMia22() { return Mia22; }
	public void setMia22(String val) { Mia22 = val; }

	private String Mia23;
	public String getMia23() { return Mia23; }
	public void setMia23(String val) { Mia23 = val; }

	private java.math.BigDecimal Mia24;
	public java.math.BigDecimal getMia24() { return Mia24; }
	public void setMia24(java.math.BigDecimal val) { Mia24 = val; }


	public void parse(EDIInputStream eis) throws IOException {
		lineNumber = eis.getCurrentSegmentNumber();
		if (log.isDebugEnabled()) log.debug("Starting segment MIA on line " + lineNumber);
		String[] fields = eis.readSegment(SEGMENT_NAME, FIELD_COUNT);
		Mia01 = eis.getDecimalValue(fields, 1, true);
		if (Mia01 == null || "".equals(fields[1].trim())) {
			eis.addError("Field 'MIA01' missing");
		}
		Mia02 = eis.getDecimalValue(fields, 2, false);
		Mia03 = eis.getDecimalValue(fields, 3, false);
		Mia04 = eis.getDecimalValue(fields, 4, false);
		Mia05 = eis.getStringValue(fields, 5, 1, 30, false);
		Mia06 = eis.getDecimalValue(fields, 6, false);
		Mia07 = eis.getDecimalValue(fields, 7, false);
		Mia08 = eis.getDecimalValue(fields, 8, false);
		Mia09 = eis.getDecimalValue(fields, 9, false);
		Mia10 = eis.getDecimalValue(fields, 10, false);
		Mia11 = eis.getDecimalValue(fields, 11, false);
		Mia12 = eis.getDecimalValue(fields, 12, false);
		Mia13 = eis.getDecimalValue(fields, 13, false);
		Mia14 = eis.getDecimalValue(fields, 14, false);
		Mia15 = eis.getDecimalValue(fields, 15, false);
		Mia16 = eis.getDecimalValue(fields, 16, false);
		Mia17 = eis.getDecimalValue(fields, 17, false);
		Mia18 = eis.getDecimalValue(fields, 18, false);
		Mia19 = eis.getDecimalValue(fields, 19, false);
		Mia20 = eis.getStringValue(fields, 20, 1, 30, false);
		Mia21 = eis.getStringValue(fields, 21, 1, 30, false);
		Mia22 = eis.getStringValue(fields, 22, 1, 30, false);
		Mia23 = eis.getStringValue(fields, 23, 1, 30, false);
		Mia24 = eis.getDecimalValue(fields, 24, false);
	}

	public void emit(EDIOutputStream eos) throws IOException {
		eos.startSegment("MIA");
		if (Mia01 == null) {
			eos.addError("Emitting null mandatory field 'MIA01'");
		}

		eos.writeField(Mia01);
		eos.writeField(Mia02);
		eos.writeField(Mia03);
		eos.writeField(Mia04);
		eos.writeField(Mia05);
		eos.writeField(Mia06);
		eos.writeField(Mia07);
		eos.writeField(Mia08);
		eos.writeField(Mia09);
		eos.writeField(Mia10);
		eos.writeField(Mia11);
		eos.writeField(Mia12);
		eos.writeField(Mia13);
		eos.writeField(Mia14);
		eos.writeField(Mia15);
		eos.writeField(Mia16);
		eos.writeField(Mia17);
		eos.writeField(Mia18);
		eos.writeField(Mia19);
		eos.writeField(Mia20);
		eos.writeField(Mia21);
		eos.writeField(Mia22);
		eos.writeField(Mia23);
		eos.writeField(Mia24);
		eos.endSegment();
	}

	public EDIElement createCopy() {
		SegmentMIA_1 copy = new SegmentMIA_1();
		copy.setLineNumber(this.lineNumber);
		copy.Mia01 = this.Mia01;
		copy.Mia02 = this.Mia02;
		copy.Mia03 = this.Mia03;
		copy.Mia04 = this.Mia04;
		copy.Mia05 = this.Mia05;
		copy.Mia06 = this.Mia06;
		copy.Mia07 = this.Mia07;
		copy.Mia08 = this.Mia08;
		copy.Mia09 = this.Mia09;
		copy.Mia10 = this.Mia10;
		copy.Mia11 = this.Mia11;
		copy.Mia12 = this.Mia12;
		copy.Mia13 = this.Mia13;
		copy.Mia14 = this.Mia14;
		copy.Mia15 = this.Mia15;
		copy.Mia16 = this.Mia16;
		copy.Mia17 = this.Mia17;
		copy.Mia18 = this.Mia18;
		copy.Mia19 = this.Mia19;
		copy.Mia20 = this.Mia20;
		copy.Mia21 = this.Mia21;
		copy.Mia22 = this.Mia22;
		copy.Mia23 = this.Mia23;
		copy.Mia24 = this.Mia24;
		return copy;
	}
}
