package com.webify.shared.edi.model.hipaa837i.beans;

import com.webify.shared.edi.model.*;
import java.io.*;
import java.util.*;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/*
 * AUTOGENERATED FILE - DO NOT EDIT!!!
 */
public class SegmentSV2_2 implements EDIElement {
	private static final Log log = LogFactory.getLog(SegmentSV2_2.class);

	public static final String SEGMENT_NAME = "SV2";
	public static final int FIELD_COUNT = 7;

	private int lineNumber = 0;
	public int getLineNumber() { return lineNumber; }
	/** Do NOT use this method - it is not public by choice... */
	public void setLineNumber(int foo) { lineNumber = foo; }

	private int ordinal = 0;
	public int getOrdinal() { return ordinal; }
	void setOrdinal(int ord) { ordinal = ord; }

	// Fields
	private String Sv201;
	public String getSv201() { return Sv201; }
	public void setSv201(String val) { Sv201 = val; }

	private CompositeC003 Sv202;
	public CompositeC003 getSv202() { return Sv202; }
	public void setSv202(CompositeC003 val) { Sv202 = val; }

	private java.math.BigDecimal Sv203;
	public java.math.BigDecimal getSv203() { return Sv203; }
	public void setSv203(java.math.BigDecimal val) { Sv203 = val; }

	private String Sv204;
	public String getSv204() { return Sv204; }
	public void setSv204(String val) {
		if (val == null) {
			throw new NullPointerException("Field 'SV204' may not be null");
		}
		if (Field355.validateValue(val)) {
			Sv204 = val;
		} else {
			throw new IllegalArgumentException("Field 'SV204' cannot have value: " + val);
		}
	}

	private java.math.BigDecimal Sv205;
	public java.math.BigDecimal getSv205() { return Sv205; }
	public void setSv205(java.math.BigDecimal val) { Sv205 = val; }

	private java.math.BigDecimal Sv206;
	public java.math.BigDecimal getSv206() { return Sv206; }
	public void setSv206(java.math.BigDecimal val) { Sv206 = val; }

	private java.math.BigDecimal Sv207;
	public java.math.BigDecimal getSv207() { return Sv207; }
	public void setSv207(java.math.BigDecimal val) { Sv207 = val; }


	public void parse(EDIInputStream eis) throws IOException {
		lineNumber = eis.getCurrentSegmentNumber();
		if (log.isDebugEnabled()) log.debug("Starting segment SV2 on line " + lineNumber);
		String[] fields = eis.readSegment(SEGMENT_NAME, FIELD_COUNT);
		Sv201 = eis.getStringValue(fields, 1, 1, 48, true);
		if (Sv201 == null || "".equals(fields[1].trim())) {
			eis.addError("Field 'SV201' missing");
		}
		if (eis.checkBounds(fields, 2, false)) {
			Sv202 = new CompositeC003();
			Sv202.setOrdinal(ordinal + "-" + 2);
			Sv202.parse(eis, fields[2]);
		}
		Sv203 = eis.getDecimalValue(fields, 3, true);
		if (Sv203 == null || "".equals(fields[3].trim())) {
			eis.addError("Field 'SV203' missing");
		}
		Sv204 = eis.getStringValue(fields, 4, 2, 2, true);
		Field355.validateInputValue(eis, "SV204", Sv204, ordinal, 4);
		if (Sv204 == null || "".equals(fields[4].trim())) {
			eis.addError("Field 'SV204' missing");
		}
		Sv205 = eis.getDecimalValue(fields, 5, true);
		if (Sv205 == null || "".equals(fields[5].trim())) {
			eis.addError("Field 'SV205' missing");
		}
		Sv206 = eis.getDecimalValue(fields, 6, false);
		Sv207 = eis.getDecimalValue(fields, 7, false);
		validate(eis);
	}

	protected void validate(EDIInputStream eis) {
		// PAIRED
		{
			int setCount = 0;
			if (Sv204 != null) setCount++;
			if (Sv205 != null) setCount++;
			if (setCount > 0 && setCount < 2) {
				eis.addError("If any of the following properties are set, all must be set: Sv204, Sv205");
			}
		}

		// REQUIRE_ONE_OF
		if (Sv201 == null && Sv202 == null) {
			eis.addError("Segment 'Sv2' requires at least one field of the following to be set: Sv201, Sv202");
		}

	}

	public void emit(EDIOutputStream eos) throws IOException {
		eos.startSegment("SV2");
		if (Sv201 == null) {
			eos.addError("Emitting null mandatory field 'SV201'");
		}

		eos.writeField(Sv201);
		if (Sv202 != null) {
			Sv202.emit(eos);
		} else {
			eos.writeNullField();
		}
		if (Sv203 == null) {
			eos.addError("Emitting null mandatory field 'SV203'");
		}

		eos.writeField(Sv203);
		if (Sv204 == null) {
			eos.addError("Emitting null mandatory field 'SV204'");
		}

		eos.writeField(Sv204);
		if (Sv205 == null) {
			eos.addError("Emitting null mandatory field 'SV205'");
		}

		eos.writeField(Sv205);
		eos.writeField(Sv206);
		eos.writeField(Sv207);
		eos.writeNullField();
		eos.writeNullField();
		eos.writeNullField();
		eos.endSegment();
	}

	public EDIElement createCopy() {
		SegmentSV2_2 copy = new SegmentSV2_2();
		copy.setLineNumber(this.lineNumber);
		copy.Sv201 = this.Sv201;
		if (getSv202() != null) copy.setSv202((CompositeC003)getSv202().createCopy());
		copy.Sv203 = this.Sv203;
		copy.Sv204 = this.Sv204;
		copy.Sv205 = this.Sv205;
		copy.Sv206 = this.Sv206;
		copy.Sv207 = this.Sv207;
		return copy;
	}
}
