package com.webify.shared.edi.model.hipaa275.beans;

import java.util.*;
import com.webify.shared.edi.model.*;

/*
 * AUTOGENERATED FILE - DO NOT EDIT!!!
 */
public class Field66 {

	private static final Object[] DEFAULT_LEGAL_VALUES = new Object[116];
	private static final Map valueOverrides = new HashMap();

	static {
		DEFAULT_LEGAL_VALUES[0] = new String[] { "0", "4" };
		DEFAULT_LEGAL_VALUES[1] = new String[] { "6", "9" };
		DEFAULT_LEGAL_VALUES[2] = new String[] { "10", "17" };
		DEFAULT_LEGAL_VALUES[3] = new String[] { "19", "51" };
		DEFAULT_LEGAL_VALUES[4] = new String[] { "53", "59" };
		DEFAULT_LEGAL_VALUES[5] = new String[] { "61", "64" };
		DEFAULT_LEGAL_VALUES[6] = new String[] { "71", "78" };
		DEFAULT_LEGAL_VALUES[7] = new String[] { "81", "83" };
		DEFAULT_LEGAL_VALUES[8] = new String[] { "90", "99" };
		DEFAULT_LEGAL_VALUES[9] = "A";
		DEFAULT_LEGAL_VALUES[10] = new String[] { "A1", "A6" };
		DEFAULT_LEGAL_VALUES[11] = new String[] { "AA", "AF" };
		DEFAULT_LEGAL_VALUES[12] = "AI";
		DEFAULT_LEGAL_VALUES[13] = "AL";
		DEFAULT_LEGAL_VALUES[14] = "AP";
		DEFAULT_LEGAL_VALUES[15] = new String[] { "BC", "BE" };
		DEFAULT_LEGAL_VALUES[16] = "BG";
		DEFAULT_LEGAL_VALUES[17] = "BP";
		DEFAULT_LEGAL_VALUES[18] = "BS";
		DEFAULT_LEGAL_VALUES[19] = "C";
		DEFAULT_LEGAL_VALUES[20] = "C1";
		DEFAULT_LEGAL_VALUES[21] = "C2";
		DEFAULT_LEGAL_VALUES[22] = "C5";
		DEFAULT_LEGAL_VALUES[23] = new String[] { "CA", "CF" };
		DEFAULT_LEGAL_VALUES[24] = "CI";
		DEFAULT_LEGAL_VALUES[25] = new String[] { "CL", "CN" };
		DEFAULT_LEGAL_VALUES[26] = "CP";
		DEFAULT_LEGAL_VALUES[27] = new String[] { "CR", "CT" };
		DEFAULT_LEGAL_VALUES[28] = "D";
		DEFAULT_LEGAL_VALUES[29] = "DG";
		DEFAULT_LEGAL_VALUES[30] = "DL";
		DEFAULT_LEGAL_VALUES[31] = new String[] { "DN", "DP" };
		DEFAULT_LEGAL_VALUES[32] = "DR";
		DEFAULT_LEGAL_VALUES[33] = "DS";
		DEFAULT_LEGAL_VALUES[34] = "E";
		DEFAULT_LEGAL_VALUES[35] = "EC";
		DEFAULT_LEGAL_VALUES[36] = "EH";
		DEFAULT_LEGAL_VALUES[37] = "EI";
		DEFAULT_LEGAL_VALUES[38] = "EL";
		DEFAULT_LEGAL_VALUES[39] = new String[] { "EP", "ET" };
		DEFAULT_LEGAL_VALUES[40] = "F";
		DEFAULT_LEGAL_VALUES[41] = new String[] { "FA", "FE" };
		DEFAULT_LEGAL_VALUES[42] = "FI";
		DEFAULT_LEGAL_VALUES[43] = "FJ";
		DEFAULT_LEGAL_VALUES[44] = "FL";
		DEFAULT_LEGAL_VALUES[45] = "FN";
		DEFAULT_LEGAL_VALUES[46] = "G";
		DEFAULT_LEGAL_VALUES[47] = "GA";
		DEFAULT_LEGAL_VALUES[48] = "GC";
		DEFAULT_LEGAL_VALUES[49] = "HC";
		DEFAULT_LEGAL_VALUES[50] = "HN";
		DEFAULT_LEGAL_VALUES[51] = "HS";
		DEFAULT_LEGAL_VALUES[52] = "I";
		DEFAULT_LEGAL_VALUES[53] = "ID";
		DEFAULT_LEGAL_VALUES[54] = "II";
		DEFAULT_LEGAL_VALUES[55] = "IP";
		DEFAULT_LEGAL_VALUES[56] = new String[] { "J", "L" };
		DEFAULT_LEGAL_VALUES[57] = new String[] { "LC", "LE" };
		DEFAULT_LEGAL_VALUES[58] = "LI";
		DEFAULT_LEGAL_VALUES[59] = "LN";
		DEFAULT_LEGAL_VALUES[60] = "M";
		DEFAULT_LEGAL_VALUES[61] = new String[] { "M3", "M6" };
		DEFAULT_LEGAL_VALUES[62] = new String[] { "MA", "MD" };
		DEFAULT_LEGAL_VALUES[63] = "MI";
		DEFAULT_LEGAL_VALUES[64] = "MK";
		DEFAULT_LEGAL_VALUES[65] = "ML";
		DEFAULT_LEGAL_VALUES[66] = "MN";
		DEFAULT_LEGAL_VALUES[67] = "MP";
		DEFAULT_LEGAL_VALUES[68] = "MR";
		DEFAULT_LEGAL_VALUES[69] = "N";
		DEFAULT_LEGAL_VALUES[70] = "NA";
		DEFAULT_LEGAL_VALUES[71] = "ND";
		DEFAULT_LEGAL_VALUES[72] = "NI";
		DEFAULT_LEGAL_VALUES[73] = "NO";
		DEFAULT_LEGAL_VALUES[74] = "NR";
		DEFAULT_LEGAL_VALUES[75] = "OC";
		DEFAULT_LEGAL_VALUES[76] = "OP";
		DEFAULT_LEGAL_VALUES[77] = new String[] { "PA", "PC" };
		DEFAULT_LEGAL_VALUES[78] = "PI";
		DEFAULT_LEGAL_VALUES[79] = "PP";
		DEFAULT_LEGAL_VALUES[80] = "PR";
		DEFAULT_LEGAL_VALUES[81] = new String[] { "RA", "RE" };
		DEFAULT_LEGAL_VALUES[82] = "RI";
		DEFAULT_LEGAL_VALUES[83] = "RP";
		DEFAULT_LEGAL_VALUES[84] = "RT";
		DEFAULT_LEGAL_VALUES[85] = "S";
		DEFAULT_LEGAL_VALUES[86] = "SA";
		DEFAULT_LEGAL_VALUES[87] = "SB";
		DEFAULT_LEGAL_VALUES[88] = "SD";
		DEFAULT_LEGAL_VALUES[89] = "SF";
		DEFAULT_LEGAL_VALUES[90] = new String[] { "SI", "SL" };
		DEFAULT_LEGAL_VALUES[91] = "SP";
		DEFAULT_LEGAL_VALUES[92] = "ST";
		DEFAULT_LEGAL_VALUES[93] = "SV";
		DEFAULT_LEGAL_VALUES[94] = "SW";
		DEFAULT_LEGAL_VALUES[95] = "TA";
		DEFAULT_LEGAL_VALUES[96] = "TC";
		DEFAULT_LEGAL_VALUES[97] = "TL";
		DEFAULT_LEGAL_VALUES[98] = "TS";
		DEFAULT_LEGAL_VALUES[99] = "TZ";
		DEFAULT_LEGAL_VALUES[100] = "UC";
		DEFAULT_LEGAL_VALUES[101] = "UI";
		DEFAULT_LEGAL_VALUES[102] = "UL";
		DEFAULT_LEGAL_VALUES[103] = "UM";
		DEFAULT_LEGAL_VALUES[104] = "UP";
		DEFAULT_LEGAL_VALUES[105] = new String[] { "UR", "UT" };
		DEFAULT_LEGAL_VALUES[106] = "WR";
		DEFAULT_LEGAL_VALUES[107] = "WS";
		DEFAULT_LEGAL_VALUES[108] = "X1";
		DEFAULT_LEGAL_VALUES[109] = "XV";
		DEFAULT_LEGAL_VALUES[110] = "XX";
		DEFAULT_LEGAL_VALUES[111] = "XY";
		DEFAULT_LEGAL_VALUES[112] = "ZC";
		DEFAULT_LEGAL_VALUES[113] = "ZN";
		DEFAULT_LEGAL_VALUES[114] = "ZY";
		DEFAULT_LEGAL_VALUES[115] = "ZZ";
		createOverrides();
	}

	public static Object[] getLegalValues(String overrideKey) {
		Object[] currentValues = (Object[]) valueOverrides.get(overrideKey);
		if (currentValues == null) {
			return DEFAULT_LEGAL_VALUES;
		}
		return currentValues;
	}

	private static void createOverrides() {
		Object[] currentValues = null;
	}

	public static boolean validateValue(String value) {
		return EDIUtils.validateValue(value, DEFAULT_LEGAL_VALUES);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, int segmentOrdinal, int fieldOrdinal) {
		String overrideKey = segmentOrdinal + "-" + fieldOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, String compositeOrdinal, int elementOrdinal) {
		String overrideKey = compositeOrdinal + "-" + elementOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}
}
