package com.webify.shared.edi.model.hipaa275.beans;

import java.util.*;
import com.webify.shared.edi.model.*;

/*
 * AUTOGENERATED FILE - DO NOT EDIT!!!
 */
public class Field640 {

	private static final Object[] DEFAULT_LEGAL_VALUES = new Object[164];
	private static final Map valueOverrides = new HashMap();

	static {
		DEFAULT_LEGAL_VALUES[0] = new String[] { "01", "31" };
		DEFAULT_LEGAL_VALUES[1] = new String[] { "33", "52" };
		DEFAULT_LEGAL_VALUES[2] = new String[] { "54", "58" };
		DEFAULT_LEGAL_VALUES[3] = "60";
		DEFAULT_LEGAL_VALUES[4] = new String[] { "62", "83" };
		DEFAULT_LEGAL_VALUES[5] = "85";
		DEFAULT_LEGAL_VALUES[6] = new String[] { "87", "89" };
		DEFAULT_LEGAL_VALUES[7] = "91";
		DEFAULT_LEGAL_VALUES[8] = "94";
		DEFAULT_LEGAL_VALUES[9] = "95";
		DEFAULT_LEGAL_VALUES[10] = new String[] { "97", "99" };
		DEFAULT_LEGAL_VALUES[11] = "3M";
		DEFAULT_LEGAL_VALUES[12] = "6A";
		DEFAULT_LEGAL_VALUES[13] = "6C";
		DEFAULT_LEGAL_VALUES[14] = "6N";
		DEFAULT_LEGAL_VALUES[15] = "6R";
		DEFAULT_LEGAL_VALUES[16] = "6S";
		DEFAULT_LEGAL_VALUES[17] = "A0";
		DEFAULT_LEGAL_VALUES[18] = "A1";
		DEFAULT_LEGAL_VALUES[19] = new String[] { "A3", "A7" };
		DEFAULT_LEGAL_VALUES[20] = new String[] { "AA", "AN" };
		DEFAULT_LEGAL_VALUES[21] = new String[] { "AP", "AT" };
		DEFAULT_LEGAL_VALUES[22] = "AV";
		DEFAULT_LEGAL_VALUES[23] = "AW";
		DEFAULT_LEGAL_VALUES[24] = new String[] { "AZ", "BB" };
		DEFAULT_LEGAL_VALUES[25] = "BD";
		DEFAULT_LEGAL_VALUES[26] = new String[] { "BF", "BH" };
		DEFAULT_LEGAL_VALUES[27] = new String[] { "BJ", "BP" };
		DEFAULT_LEGAL_VALUES[28] = new String[] { "BR", "BX" };
		DEFAULT_LEGAL_VALUES[29] = "BZ";
		DEFAULT_LEGAL_VALUES[30] = new String[] { "C0", "C7" };
		DEFAULT_LEGAL_VALUES[31] = new String[] { "CA", "CP" };
		DEFAULT_LEGAL_VALUES[32] = new String[] { "CR", "CZ" };
		DEFAULT_LEGAL_VALUES[33] = "D1";
		DEFAULT_LEGAL_VALUES[34] = "D4";
		DEFAULT_LEGAL_VALUES[35] = new String[] { "DA", "DI" };
		DEFAULT_LEGAL_VALUES[36] = new String[] { "DK", "DU" };
		DEFAULT_LEGAL_VALUES[37] = "E1";
		DEFAULT_LEGAL_VALUES[38] = new String[] { "EA", "ED" };
		DEFAULT_LEGAL_VALUES[39] = "EF";
		DEFAULT_LEGAL_VALUES[40] = "EI";
		DEFAULT_LEGAL_VALUES[41] = "EM";
		DEFAULT_LEGAL_VALUES[42] = "EP";
		DEFAULT_LEGAL_VALUES[43] = "ER";
		DEFAULT_LEGAL_VALUES[44] = "EX";
		DEFAULT_LEGAL_VALUES[45] = "F1";
		DEFAULT_LEGAL_VALUES[46] = new String[] { "F4", "F7" };
		DEFAULT_LEGAL_VALUES[47] = new String[] { "FA", "FG" };
		DEFAULT_LEGAL_VALUES[48] = "FI";
		DEFAULT_LEGAL_VALUES[49] = new String[] { "FL", "FN" };
		DEFAULT_LEGAL_VALUES[50] = "FP";
		DEFAULT_LEGAL_VALUES[51] = new String[] { "FR", "FT" };
		DEFAULT_LEGAL_VALUES[52] = new String[] { "G1", "G3" };
		DEFAULT_LEGAL_VALUES[53] = "GA";
		DEFAULT_LEGAL_VALUES[54] = "GI";
		DEFAULT_LEGAL_VALUES[55] = new String[] { "GR", "GY" };
		DEFAULT_LEGAL_VALUES[56] = new String[] { "HA", "HG" };
		DEFAULT_LEGAL_VALUES[57] = "HP";
		DEFAULT_LEGAL_VALUES[58] = "I1";
		DEFAULT_LEGAL_VALUES[59] = new String[] { "IA", "IF" };
		DEFAULT_LEGAL_VALUES[60] = "II";
		DEFAULT_LEGAL_VALUES[61] = new String[] { "IM", "IO" };
		DEFAULT_LEGAL_VALUES[62] = "IR";
		DEFAULT_LEGAL_VALUES[63] = "IU";
		DEFAULT_LEGAL_VALUES[64] = "IW";
		DEFAULT_LEGAL_VALUES[65] = "IX";
		DEFAULT_LEGAL_VALUES[66] = "IZ";
		DEFAULT_LEGAL_VALUES[67] = "JM";
		DEFAULT_LEGAL_VALUES[68] = "JO";
		DEFAULT_LEGAL_VALUES[69] = "JR";
		DEFAULT_LEGAL_VALUES[70] = "JS";
		DEFAULT_LEGAL_VALUES[71] = "JU";
		DEFAULT_LEGAL_VALUES[72] = "JX";
		DEFAULT_LEGAL_VALUES[73] = new String[] { "KB", "KN" };
		DEFAULT_LEGAL_VALUES[74] = "KS";
		DEFAULT_LEGAL_VALUES[75] = "KT";
		DEFAULT_LEGAL_VALUES[76] = new String[] { "LC", "LF" };
		DEFAULT_LEGAL_VALUES[77] = new String[] { "LN", "LP" };
		DEFAULT_LEGAL_VALUES[78] = "LR";
		DEFAULT_LEGAL_VALUES[79] = "LV";
		DEFAULT_LEGAL_VALUES[80] = "M1";
		DEFAULT_LEGAL_VALUES[81] = new String[] { "MA", "MF" };
		DEFAULT_LEGAL_VALUES[82] = "MI";
		DEFAULT_LEGAL_VALUES[83] = "ML";
		DEFAULT_LEGAL_VALUES[84] = "MM";
		DEFAULT_LEGAL_VALUES[85] = "MP";
		DEFAULT_LEGAL_VALUES[86] = "MR";
		DEFAULT_LEGAL_VALUES[87] = "MS";
		DEFAULT_LEGAL_VALUES[88] = "MU";
		DEFAULT_LEGAL_VALUES[89] = new String[] { "N1", "N8" };
		DEFAULT_LEGAL_VALUES[90] = new String[] { "NA", "NM" };
		DEFAULT_LEGAL_VALUES[91] = new String[] { "NO", "NU" };
		DEFAULT_LEGAL_VALUES[92] = "OC";
		DEFAULT_LEGAL_VALUES[93] = "OF";
		DEFAULT_LEGAL_VALUES[94] = "OP";
		DEFAULT_LEGAL_VALUES[95] = "OR";
		DEFAULT_LEGAL_VALUES[96] = "P1";
		DEFAULT_LEGAL_VALUES[97] = new String[] { "PA", "PI" };
		DEFAULT_LEGAL_VALUES[98] = "PL";
		DEFAULT_LEGAL_VALUES[99] = "PM";
		DEFAULT_LEGAL_VALUES[100] = "PO";
		DEFAULT_LEGAL_VALUES[101] = "PP";
		DEFAULT_LEGAL_VALUES[102] = new String[] { "PR", "PX" };
		DEFAULT_LEGAL_VALUES[103] = "PZ";
		DEFAULT_LEGAL_VALUES[104] = "Q1";
		DEFAULT_LEGAL_VALUES[105] = "Q2";
		DEFAULT_LEGAL_VALUES[106] = new String[] { "QA", "QH" };
		DEFAULT_LEGAL_VALUES[107] = new String[] { "QJ", "QL" };
		DEFAULT_LEGAL_VALUES[108] = "QP";
		DEFAULT_LEGAL_VALUES[109] = "QR";
		DEFAULT_LEGAL_VALUES[110] = new String[] { "R1", "R8" };
		DEFAULT_LEGAL_VALUES[111] = new String[] { "RA", "RK" };
		DEFAULT_LEGAL_VALUES[112] = "RM";
		DEFAULT_LEGAL_VALUES[113] = "RP";
		DEFAULT_LEGAL_VALUES[114] = "RQ";
		DEFAULT_LEGAL_VALUES[115] = new String[] { "RS", "RU" };
		DEFAULT_LEGAL_VALUES[116] = "RZ";
		DEFAULT_LEGAL_VALUES[117] = new String[] { "S1", "S4" };
		DEFAULT_LEGAL_VALUES[118] = new String[] { "SA", "SH" };
		DEFAULT_LEGAL_VALUES[119] = "SL";
		DEFAULT_LEGAL_VALUES[120] = "SM";
		DEFAULT_LEGAL_VALUES[121] = new String[] { "SO", "SV" };
		DEFAULT_LEGAL_VALUES[122] = new String[] { "T1", "T9" };
		DEFAULT_LEGAL_VALUES[123] = "TD";
		DEFAULT_LEGAL_VALUES[124] = new String[] { "TF", "TL" };
		DEFAULT_LEGAL_VALUES[125] = "TP";
		DEFAULT_LEGAL_VALUES[126] = new String[] { "TR", "TT" };
		DEFAULT_LEGAL_VALUES[127] = "TX";
		DEFAULT_LEGAL_VALUES[128] = "U1";
		DEFAULT_LEGAL_VALUES[129] = "U2";
		DEFAULT_LEGAL_VALUES[130] = "U4";
		DEFAULT_LEGAL_VALUES[131] = "U5";
		DEFAULT_LEGAL_VALUES[132] = "U9";
		DEFAULT_LEGAL_VALUES[133] = "UA";
		DEFAULT_LEGAL_VALUES[134] = "UC";
		DEFAULT_LEGAL_VALUES[135] = "UD";
		DEFAULT_LEGAL_VALUES[136] = "UF";
		DEFAULT_LEGAL_VALUES[137] = "UI";
		DEFAULT_LEGAL_VALUES[138] = "UM";
		DEFAULT_LEGAL_VALUES[139] = "UO";
		DEFAULT_LEGAL_VALUES[140] = "UP";
		DEFAULT_LEGAL_VALUES[141] = "UR";
		DEFAULT_LEGAL_VALUES[142] = "UT";
		DEFAULT_LEGAL_VALUES[143] = new String[] { "V1", "V4" };
		DEFAULT_LEGAL_VALUES[144] = "VH";
		DEFAULT_LEGAL_VALUES[145] = "VJ";
		DEFAULT_LEGAL_VALUES[146] = new String[] { "VL", "VR" };
		DEFAULT_LEGAL_VALUES[147] = "W1";
		DEFAULT_LEGAL_VALUES[148] = "W4";
		DEFAULT_LEGAL_VALUES[149] = "W5";
		DEFAULT_LEGAL_VALUES[150] = "WA";
		DEFAULT_LEGAL_VALUES[151] = "WC";
		DEFAULT_LEGAL_VALUES[152] = "WD";
		DEFAULT_LEGAL_VALUES[153] = "WH";
		DEFAULT_LEGAL_VALUES[154] = "WO";
		DEFAULT_LEGAL_VALUES[155] = "WS";
		DEFAULT_LEGAL_VALUES[156] = "WT";
		DEFAULT_LEGAL_VALUES[157] = "X1";
		DEFAULT_LEGAL_VALUES[158] = new String[] { "XA", "XD" };
		DEFAULT_LEGAL_VALUES[159] = new String[] { "XX", "XZ" };
		DEFAULT_LEGAL_VALUES[160] = "YI";
		DEFAULT_LEGAL_VALUES[161] = "YR";
		DEFAULT_LEGAL_VALUES[162] = new String[] { "Z1", "Z4" };
		DEFAULT_LEGAL_VALUES[163] = new String[] { "ZA", "ZZ" };
		createOverrides();
	}

	public static Object[] getLegalValues(String overrideKey) {
		Object[] currentValues = (Object[]) valueOverrides.get(overrideKey);
		if (currentValues == null) {
			return DEFAULT_LEGAL_VALUES;
		}
		return currentValues;
	}

	private static void createOverrides() {
		Object[] currentValues = null;
	}

	public static boolean validateValue(String value) {
		return EDIUtils.validateValue(value, DEFAULT_LEGAL_VALUES);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, int segmentOrdinal, int fieldOrdinal) {
		String overrideKey = segmentOrdinal + "-" + fieldOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, String compositeOrdinal, int elementOrdinal) {
		String overrideKey = compositeOrdinal + "-" + elementOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}
}
