package com.webify.shared.edi.model.hipaa275.beans;

import java.util.*;
import com.webify.shared.edi.model.*;

/*
 * AUTOGENERATED FILE - DO NOT EDIT!!!
 */
public class Field374 {

	private static final Object[] DEFAULT_LEGAL_VALUES = new Object[138];
	private static final Map valueOverrides = new HashMap();

	static {
		DEFAULT_LEGAL_VALUES[0] = new String[] { "001", "116" };
		DEFAULT_LEGAL_VALUES[1] = new String[] { "118", "122" };
		DEFAULT_LEGAL_VALUES[2] = new String[] { "124", "406" };
		DEFAULT_LEGAL_VALUES[3] = new String[] { "408", "587" };
		DEFAULT_LEGAL_VALUES[4] = new String[] { "589", "604" };
		DEFAULT_LEGAL_VALUES[5] = new String[] { "606", "627" };
		DEFAULT_LEGAL_VALUES[6] = new String[] { "629", "638" };
		DEFAULT_LEGAL_VALUES[7] = new String[] { "640", "644" };
		DEFAULT_LEGAL_VALUES[8] = new String[] { "646", "653" };
		DEFAULT_LEGAL_VALUES[9] = new String[] { "655", "675" };
		DEFAULT_LEGAL_VALUES[10] = new String[] { "681", "697" };
		DEFAULT_LEGAL_VALUES[11] = new String[] { "699", "734" };
		DEFAULT_LEGAL_VALUES[12] = new String[] { "736", "762" };
		DEFAULT_LEGAL_VALUES[13] = new String[] { "764", "766" };
		DEFAULT_LEGAL_VALUES[14] = new String[] { "769", "828" };
		DEFAULT_LEGAL_VALUES[15] = new String[] { "830", "832" };
		DEFAULT_LEGAL_VALUES[16] = new String[] { "840", "851" };
		DEFAULT_LEGAL_VALUES[17] = new String[] { "853", "885" };
		DEFAULT_LEGAL_VALUES[18] = "900";
		DEFAULT_LEGAL_VALUES[19] = "901";
		DEFAULT_LEGAL_VALUES[20] = new String[] { "903", "957" };
		DEFAULT_LEGAL_VALUES[21] = new String[] { "960", "990" };
		DEFAULT_LEGAL_VALUES[22] = new String[] { "992", "999" };
		DEFAULT_LEGAL_VALUES[23] = new String[] { "AA1", "AA9" };
		DEFAULT_LEGAL_VALUES[24] = new String[] { "AAA", "AAZ" };
		DEFAULT_LEGAL_VALUES[25] = new String[] { "AB1", "AB9" };
		DEFAULT_LEGAL_VALUES[26] = new String[] { "ABA", "ABI" };
		DEFAULT_LEGAL_VALUES[27] = new String[] { "ABK", "ABY" };
		DEFAULT_LEGAL_VALUES[28] = new String[] { "ACA", "ACX" };
		DEFAULT_LEGAL_VALUES[29] = new String[] { "ACZ", "ADN" };
		DEFAULT_LEGAL_VALUES[30] = new String[] { "ADR", "ADY" };
		DEFAULT_LEGAL_VALUES[31] = new String[] { "AEA", "AEI" };
		DEFAULT_LEGAL_VALUES[32] = new String[] { "AEK", "AEY" };
		DEFAULT_LEGAL_VALUES[33] = "ARD";
		DEFAULT_LEGAL_VALUES[34] = "AWH";
		DEFAULT_LEGAL_VALUES[35] = new String[] { "BAA", "BAR" };
		DEFAULT_LEGAL_VALUES[36] = "CAD";
		DEFAULT_LEGAL_VALUES[37] = "CCR";
		DEFAULT_LEGAL_VALUES[38] = "CDT";
		DEFAULT_LEGAL_VALUES[39] = new String[] { "CEA", "CEF" };
		DEFAULT_LEGAL_VALUES[40] = "CEH";
		DEFAULT_LEGAL_VALUES[41] = new String[] { "CEJ", "CEO" };
		DEFAULT_LEGAL_VALUES[42] = "CLO";
		DEFAULT_LEGAL_VALUES[43] = "CLU";
		DEFAULT_LEGAL_VALUES[44] = "COM";
		DEFAULT_LEGAL_VALUES[45] = "CON";
		DEFAULT_LEGAL_VALUES[46] = "CUR";
		DEFAULT_LEGAL_VALUES[47] = "DAF";
		DEFAULT_LEGAL_VALUES[48] = "DDO";
		DEFAULT_LEGAL_VALUES[49] = "DEE";
		DEFAULT_LEGAL_VALUES[50] = "DEL";
		DEFAULT_LEGAL_VALUES[51] = "DET";
		DEFAULT_LEGAL_VALUES[52] = "DFF";
		DEFAULT_LEGAL_VALUES[53] = "DFS";
		DEFAULT_LEGAL_VALUES[54] = "DIS";
		DEFAULT_LEGAL_VALUES[55] = "DLC";
		DEFAULT_LEGAL_VALUES[56] = "DOA";
		DEFAULT_LEGAL_VALUES[57] = "DOD";
		DEFAULT_LEGAL_VALUES[58] = "DOI";
		DEFAULT_LEGAL_VALUES[59] = "DOR";
		DEFAULT_LEGAL_VALUES[60] = "DSP";
		DEFAULT_LEGAL_VALUES[61] = new String[] { "E01", "E07" };
		DEFAULT_LEGAL_VALUES[62] = "ECD";
		DEFAULT_LEGAL_VALUES[63] = "ECF";
		DEFAULT_LEGAL_VALUES[64] = "ECS";
		DEFAULT_LEGAL_VALUES[65] = "ECT";
		DEFAULT_LEGAL_VALUES[66] = new String[] { "EDA", "EDP" };
		DEFAULT_LEGAL_VALUES[67] = "EPP";
		DEFAULT_LEGAL_VALUES[68] = "ESC";
		DEFAULT_LEGAL_VALUES[69] = "ESF";
		DEFAULT_LEGAL_VALUES[70] = "ESS";
		DEFAULT_LEGAL_VALUES[71] = "EST";
		DEFAULT_LEGAL_VALUES[72] = "ETP";
		DEFAULT_LEGAL_VALUES[73] = "EXO";
		DEFAULT_LEGAL_VALUES[74] = "EXP";
		DEFAULT_LEGAL_VALUES[75] = "FFI";
		DEFAULT_LEGAL_VALUES[76] = "FFO";
		DEFAULT_LEGAL_VALUES[77] = "GRD";
		DEFAULT_LEGAL_VALUES[78] = "ICF";
		DEFAULT_LEGAL_VALUES[79] = "IDG";
		DEFAULT_LEGAL_VALUES[80] = "III";
		DEFAULT_LEGAL_VALUES[81] = "IMP";
		DEFAULT_LEGAL_VALUES[82] = "INC";
		DEFAULT_LEGAL_VALUES[83] = "INT";
		DEFAULT_LEGAL_VALUES[84] = "KEV";
		DEFAULT_LEGAL_VALUES[85] = "KEW";
		DEFAULT_LEGAL_VALUES[86] = "LAM";
		DEFAULT_LEGAL_VALUES[87] = "LAS";
		DEFAULT_LEGAL_VALUES[88] = "LCC";
		DEFAULT_LEGAL_VALUES[89] = "LEA";
		DEFAULT_LEGAL_VALUES[90] = "LEL";
		DEFAULT_LEGAL_VALUES[91] = "LIQ";
		DEFAULT_LEGAL_VALUES[92] = "LLP";
		DEFAULT_LEGAL_VALUES[93] = "LOG";
		DEFAULT_LEGAL_VALUES[94] = "LPC";
		DEFAULT_LEGAL_VALUES[95] = "LSC";
		DEFAULT_LEGAL_VALUES[96] = "LTP";
		DEFAULT_LEGAL_VALUES[97] = "MRR";
		DEFAULT_LEGAL_VALUES[98] = "MSD";
		DEFAULT_LEGAL_VALUES[99] = "NAM";
		DEFAULT_LEGAL_VALUES[100] = "NFD";
		DEFAULT_LEGAL_VALUES[101] = "NRG";
		DEFAULT_LEGAL_VALUES[102] = "NSD";
		DEFAULT_LEGAL_VALUES[103] = "ORG";
		DEFAULT_LEGAL_VALUES[104] = "PBC";
		DEFAULT_LEGAL_VALUES[105] = "PDV";
		DEFAULT_LEGAL_VALUES[106] = "PLS";
		DEFAULT_LEGAL_VALUES[107] = "PPD";
		DEFAULT_LEGAL_VALUES[108] = "PPP";
		DEFAULT_LEGAL_VALUES[109] = "PRD";
		DEFAULT_LEGAL_VALUES[110] = "PRR";
		DEFAULT_LEGAL_VALUES[111] = "PTD";
		DEFAULT_LEGAL_VALUES[112] = "PTO";
		DEFAULT_LEGAL_VALUES[113] = "RAP";
		DEFAULT_LEGAL_VALUES[114] = "RES";
		DEFAULT_LEGAL_VALUES[115] = "RFD";
		DEFAULT_LEGAL_VALUES[116] = "RFF";
		DEFAULT_LEGAL_VALUES[117] = "RFO";
		DEFAULT_LEGAL_VALUES[118] = "RNT";
		DEFAULT_LEGAL_VALUES[119] = "RRM";
		DEFAULT_LEGAL_VALUES[120] = "RRT";
		DEFAULT_LEGAL_VALUES[121] = "RSD";
		DEFAULT_LEGAL_VALUES[122] = "RSS";
		DEFAULT_LEGAL_VALUES[123] = "RTO";
		DEFAULT_LEGAL_VALUES[124] = "SCV";
		DEFAULT_LEGAL_VALUES[125] = "SDD";
		DEFAULT_LEGAL_VALUES[126] = "STN";
		DEFAULT_LEGAL_VALUES[127] = new String[] { "TSR", "TST" };
		DEFAULT_LEGAL_VALUES[128] = "VAT";
		DEFAULT_LEGAL_VALUES[129] = "VLU";
		DEFAULT_LEGAL_VALUES[130] = new String[] { "W01", "W03" };
		DEFAULT_LEGAL_VALUES[131] = new String[] { "W05", "W09" };
		DEFAULT_LEGAL_VALUES[132] = new String[] { "W10", "W13" };
		DEFAULT_LEGAL_VALUES[133] = "WAA";
		DEFAULT_LEGAL_VALUES[134] = "WAY";
		DEFAULT_LEGAL_VALUES[135] = "YXX";
		DEFAULT_LEGAL_VALUES[136] = "YXY";
		DEFAULT_LEGAL_VALUES[137] = "ZZZ";
		createOverrides();
	}

	public static Object[] getLegalValues(String overrideKey) {
		Object[] currentValues = (Object[]) valueOverrides.get(overrideKey);
		if (currentValues == null) {
			return DEFAULT_LEGAL_VALUES;
		}
		return currentValues;
	}

	private static void createOverrides() {
		Object[] currentValues = null;
	}

	public static boolean validateValue(String value) {
		return EDIUtils.validateValue(value, DEFAULT_LEGAL_VALUES);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, int segmentOrdinal, int fieldOrdinal) {
		String overrideKey = segmentOrdinal + "-" + fieldOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, String compositeOrdinal, int elementOrdinal) {
		String overrideKey = compositeOrdinal + "-" + elementOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}
}
