package com.webify.shared.edi.model.hipaa275.beans;

import java.util.*;
import com.webify.shared.edi.model.*;

/*
 * AUTOGENERATED FILE - DO NOT EDIT!!!
 */
public class Field1131 {

	private static final Object[] DEFAULT_LEGAL_VALUES = new Object[44];
	private static final Map valueOverrides = new HashMap();

	static {
		DEFAULT_LEGAL_VALUES[0] = new String[] { "01", "12" };
		DEFAULT_LEGAL_VALUES[1] = new String[] { "14", "42" };
		DEFAULT_LEGAL_VALUES[2] = "0A";
		DEFAULT_LEGAL_VALUES[3] = "0K";
		DEFAULT_LEGAL_VALUES[4] = new String[] { "AA", "AD" };
		DEFAULT_LEGAL_VALUES[5] = "AS";
		DEFAULT_LEGAL_VALUES[6] = "BD";
		DEFAULT_LEGAL_VALUES[7] = "C2";
		DEFAULT_LEGAL_VALUES[8] = "CL";
		DEFAULT_LEGAL_VALUES[9] = "DD";
		DEFAULT_LEGAL_VALUES[10] = "EL";
		DEFAULT_LEGAL_VALUES[11] = "EM";
		DEFAULT_LEGAL_VALUES[12] = "EX";
		DEFAULT_LEGAL_VALUES[13] = "FL";
		DEFAULT_LEGAL_VALUES[14] = "FP";
		DEFAULT_LEGAL_VALUES[15] = new String[] { "FT", "FV" };
		DEFAULT_LEGAL_VALUES[16] = "GR";
		DEFAULT_LEGAL_VALUES[17] = "HG";
		DEFAULT_LEGAL_VALUES[18] = "HS";
		DEFAULT_LEGAL_VALUES[19] = "IF";
		DEFAULT_LEGAL_VALUES[20] = "IN";
		DEFAULT_LEGAL_VALUES[21] = "LA";
		DEFAULT_LEGAL_VALUES[22] = "MD";
		DEFAULT_LEGAL_VALUES[23] = "MG";
		DEFAULT_LEGAL_VALUES[24] = "MS";
		DEFAULT_LEGAL_VALUES[25] = "NO";
		DEFAULT_LEGAL_VALUES[26] = new String[] { "P0", "P5" };
		DEFAULT_LEGAL_VALUES[27] = "PC";
		DEFAULT_LEGAL_VALUES[28] = "PD";
		DEFAULT_LEGAL_VALUES[29] = "PF";
		DEFAULT_LEGAL_VALUES[30] = "PK";
		DEFAULT_LEGAL_VALUES[31] = "PM";
		DEFAULT_LEGAL_VALUES[32] = "PO";
		DEFAULT_LEGAL_VALUES[33] = "PS";
		DEFAULT_LEGAL_VALUES[34] = "SA";
		DEFAULT_LEGAL_VALUES[35] = "SP";
		DEFAULT_LEGAL_VALUES[36] = "SS";
		DEFAULT_LEGAL_VALUES[37] = "ST";
		DEFAULT_LEGAL_VALUES[38] = "TF";
		DEFAULT_LEGAL_VALUES[39] = "TW";
		DEFAULT_LEGAL_VALUES[40] = "UG";
		DEFAULT_LEGAL_VALUES[41] = "UN";
		DEFAULT_LEGAL_VALUES[42] = "VR";
		DEFAULT_LEGAL_VALUES[43] = "VS";
		createOverrides();
	}

	public static Object[] getLegalValues(String overrideKey) {
		Object[] currentValues = (Object[]) valueOverrides.get(overrideKey);
		if (currentValues == null) {
			return DEFAULT_LEGAL_VALUES;
		}
		return currentValues;
	}

	private static void createOverrides() {
		Object[] currentValues = null;
	}

	public static boolean validateValue(String value) {
		return EDIUtils.validateValue(value, DEFAULT_LEGAL_VALUES);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, int segmentOrdinal, int fieldOrdinal) {
		String overrideKey = segmentOrdinal + "-" + fieldOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, String compositeOrdinal, int elementOrdinal) {
		String overrideKey = compositeOrdinal + "-" + elementOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}
}
