package com.webify.shared.edi.model.hipaa275.beans;

import com.webify.shared.edi.model.*;
import java.io.*;
import java.util.*;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/*
 * AUTOGENERATED FILE - DO NOT EDIT!!!
 */
public class SegmentSTC implements EDIElement {
	private static final Log log = LogFactory.getLog(SegmentSTC.class);

	public static final String SEGMENT_NAME = "STC";
	public static final int FIELD_COUNT = 12;

	private int lineNumber = 0;
	public int getLineNumber() { return lineNumber; }
	/** Do NOT use this method - it is not public by choice... */
	public void setLineNumber(int foo) { lineNumber = foo; }

	private int ordinal = 0;
	public int getOrdinal() { return ordinal; }
	void setOrdinal(int ord) { ordinal = ord; }

	// Fields
	private CompositeC043 Stc01;
	public CompositeC043 getStc01() { return Stc01; }
	public void setStc01(CompositeC043 val) { Stc01 = val; }

	private Date Stc02;
	public Date getStc02() { return Stc02; }
	public void setStc02(Date val) { Stc02 = val; }

	private String Stc03;
	public String getStc03() { return Stc03; }
	public void setStc03(String val) {
		if (Field306.validateValue(val)) {
			Stc03 = val;
		} else {
			throw new IllegalArgumentException("Field 'STC03' cannot have value: " + val);
		}
	}

	private java.math.BigDecimal Stc04;
	public java.math.BigDecimal getStc04() { return Stc04; }
	public void setStc04(java.math.BigDecimal val) { Stc04 = val; }

	private java.math.BigDecimal Stc05;
	public java.math.BigDecimal getStc05() { return Stc05; }
	public void setStc05(java.math.BigDecimal val) { Stc05 = val; }

	private Date Stc06;
	public Date getStc06() { return Stc06; }
	public void setStc06(Date val) { Stc06 = val; }

	private String Stc07;
	public String getStc07() { return Stc07; }
	public void setStc07(String val) {
		if (Field591.validateValue(val)) {
			Stc07 = val;
		} else {
			throw new IllegalArgumentException("Field 'STC07' cannot have value: " + val);
		}
	}

	private Date Stc08;
	public Date getStc08() { return Stc08; }
	public void setStc08(Date val) { Stc08 = val; }

	private String Stc09;
	public String getStc09() { return Stc09; }
	public void setStc09(String val) { Stc09 = val; }

	private CompositeC043 Stc10;
	public CompositeC043 getStc10() { return Stc10; }
	public void setStc10(CompositeC043 val) { Stc10 = val; }

	private CompositeC043 Stc11;
	public CompositeC043 getStc11() { return Stc11; }
	public void setStc11(CompositeC043 val) { Stc11 = val; }

	private String Stc12;
	public String getStc12() { return Stc12; }
	public void setStc12(String val) { Stc12 = val; }


	public void parse(EDIInputStream eis) throws IOException {
		lineNumber = eis.getCurrentSegmentNumber();
		if (log.isDebugEnabled()) log.debug("Starting segment STC on line " + lineNumber);
		String[] fields = eis.readSegment(SEGMENT_NAME, FIELD_COUNT);
		if (eis.checkBounds(fields, 1, true)) {
			Stc01 = new CompositeC043();
			Stc01.setOrdinal(ordinal + "-" + 1);
			Stc01.parse(eis, fields[1]);
		}
		if (Stc01 == null || "".equals(fields[1].trim())) {
			eis.addError("Field 'STC01' missing");
		}
		Stc02 = eis.getDateValue(fields, 2, false);
		Stc03 = eis.getStringValue(fields, 3, 1, 2, false);
		Field306.validateInputValue(eis, "STC03", Stc03, ordinal, 3);
		Stc04 = eis.getDecimalValue(fields, 4, false);
		Stc05 = eis.getDecimalValue(fields, 5, false);
		Stc06 = eis.getDateValue(fields, 6, false);
		Stc07 = eis.getStringValue(fields, 7, 3, 3, false);
		Field591.validateInputValue(eis, "STC07", Stc07, ordinal, 7);
		Stc08 = eis.getDateValue(fields, 8, false);
		Stc09 = eis.getStringValue(fields, 9, 1, 16, false);
		if (eis.checkBounds(fields, 10, false)) {
			Stc10 = new CompositeC043();
			Stc10.setOrdinal(ordinal + "-" + 10);
			Stc10.parse(eis, fields[10]);
		}
		if (eis.checkBounds(fields, 11, false)) {
			Stc11 = new CompositeC043();
			Stc11.setOrdinal(ordinal + "-" + 11);
			Stc11.parse(eis, fields[11]);
		}
		Stc12 = eis.getStringValue(fields, 12, 1, 264, false);
	}

	public void emit(EDIOutputStream eos) throws IOException {
		eos.startSegment("STC");
		if (Stc01 == null) {
			eos.addError("Emitting null mandatory field 'STC01'");
		}

		if (Stc01 != null) {
			Stc01.emit(eos);
		} else {
			eos.writeNullField();
		}
		eos.writeField(Stc02);
		eos.writeField(Stc03);
		eos.writeField(Stc04);
		eos.writeField(Stc05);
		eos.writeField(Stc06);
		eos.writeField(Stc07);
		eos.writeField(Stc08);
		eos.writeField(Stc09);
		if (Stc10 != null) {
			Stc10.emit(eos);
		} else {
			eos.writeNullField();
		}
		if (Stc11 != null) {
			Stc11.emit(eos);
		} else {
			eos.writeNullField();
		}
		eos.writeField(Stc12);
		eos.endSegment();
	}

	public EDIElement createCopy() {
		SegmentSTC copy = new SegmentSTC();
		copy.setLineNumber(this.lineNumber);
		if (getStc01() != null) copy.setStc01((CompositeC043)getStc01().createCopy());
		copy.Stc02 = this.Stc02;
		copy.Stc03 = this.Stc03;
		copy.Stc04 = this.Stc04;
		copy.Stc05 = this.Stc05;
		copy.Stc06 = this.Stc06;
		copy.Stc07 = this.Stc07;
		copy.Stc08 = this.Stc08;
		copy.Stc09 = this.Stc09;
		if (getStc10() != null) copy.setStc10((CompositeC043)getStc10().createCopy());
		if (getStc11() != null) copy.setStc11((CompositeC043)getStc11().createCopy());
		copy.Stc12 = this.Stc12;
		return copy;
	}
}
