package com.webify.shared.edi.model.hipaa997.beans;

import com.webify.shared.edi.model.*;
import java.io.*;
import java.util.*;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/*
 * AUTOGENERATED FILE - DO NOT EDIT!!!
 */
public class SegmentAK1 implements EDIElement {
	private static final Log log = LogFactory.getLog(SegmentAK1.class);

	public static final String SEGMENT_NAME = "AK1";
	public static final int FIELD_COUNT = 2;

	private int lineNumber = 0;
	public int getLineNumber() { return lineNumber; }
	/** Do NOT use this method - it is not public by choice... */
	public void setLineNumber(int foo) { lineNumber = foo; }

	private int ordinal = 0;
	public int getOrdinal() { return ordinal; }
	void setOrdinal(int ord) { ordinal = ord; }

	// Fields
	private String Ak101;
	public String getAk101() { return Ak101; }
	public void setAk101(String val) {
		if (val == null) {
			throw new NullPointerException("Field 'AK101' may not be null");
		}
		if (Field479.validateValue(val)) {
			Ak101 = val;
		} else {
			throw new IllegalArgumentException("Field 'AK101' cannot have value: " + val);
		}
	}

	private Integer Ak102;
	public Integer getAk102() { return Ak102; }
	public void setAk102(Integer val) { Ak102 = val; }


	public void parse(EDIInputStream eis) throws IOException {
		lineNumber = eis.getCurrentSegmentNumber();
		if (log.isDebugEnabled()) log.debug("Starting segment AK1 on line " + lineNumber);
		String[] fields = eis.readSegment(SEGMENT_NAME, FIELD_COUNT);
		Ak101 = eis.getStringValue(fields, 1, 2, 2, true);
		Field479.validateInputValue(eis, "AK101", Ak101, ordinal, 1);
		if (Ak101 == null || "".equals(fields[1].trim())) {
			eis.addError("Field 'AK101' missing");
		}
		Ak102 = eis.getIntegerValue(fields, 2, true);
		if (Ak102 == null || "".equals(fields[2].trim())) {
			eis.addError("Field 'AK102' missing");
		}
	}

	public void emit(EDIOutputStream eos) throws IOException {
		eos.startSegment("AK1");
		if (Ak101 == null) {
			eos.addError("Emitting null mandatory field 'AK101'");
		}

		eos.writeField(Ak101);
		if (Ak102 == null) {
			eos.addError("Emitting null mandatory field 'AK102'");
		}

		eos.writeField(Ak102);
		eos.endSegment();
	}

	public EDIElement createCopy() {
		SegmentAK1 copy = new SegmentAK1();
		copy.setLineNumber(this.lineNumber);
		copy.Ak101 = this.Ak101;
		copy.Ak102 = this.Ak102;
		return copy;
	}
}
