package com.webify.shared.edi.model.hipaa837p.beans;

import com.webify.shared.edi.model.*;
import java.io.IOException;

/*
 * AUTOGENERATED FILE - DO NOT EDIT!!!
 */
public class CompositeC024_1 implements EDICompositeField {

	public static final String COMPOSITE_NAME = "C024";
	public static final int ELEMENT_COUNT = 5;

	private String ordinal = null;
	void setOrdinal(String ord) { ordinal = ord; }

	// Elements
	private String C024_01;
	public String getC024_01() { return C024_01; }
	public void setC024_01(String val) {
		if (Field1362.validateValue(val)) {
			C024_01 = val;
		} else {
			throw new IllegalArgumentException("Field 'C024_01' cannot have value: " + val);
		}
	}

	private String C024_02;
	public String getC024_02() { return C024_02; }
	public void setC024_02(String val) {
		if (Field1362.validateValue(val)) {
			C024_02 = val;
		} else {
			throw new IllegalArgumentException("Field 'C024_02' cannot have value: " + val);
		}
	}

	private String C024_03;
	public String getC024_03() { return C024_03; }
	public void setC024_03(String val) {
		if (Field1362.validateValue(val)) {
			C024_03 = val;
		} else {
			throw new IllegalArgumentException("Field 'C024_03' cannot have value: " + val);
		}
	}

	private String C024_04;
	public String getC024_04() { return C024_04; }
	public void setC024_04(String val) { C024_04 = val; }

	private String C024_05;
	public String getC024_05() { return C024_05; }
	public void setC024_05(String val) { C024_05 = val; }

	public String[] getElements() {
		String[] values = new String[ELEMENT_COUNT];
		values[0] = EDIUtils.stringValue(C024_01);
		values[1] = EDIUtils.stringValue(C024_02);
		values[2] = EDIUtils.stringValue(C024_03);
		values[3] = EDIUtils.stringValue(C024_04);
		values[4] = EDIUtils.stringValue(C024_05);
		return values;
	}

	public void setElements(String[] values) throws EDIParseException {
		if (values == null || values.length != ELEMENT_COUNT) {
			throw new EDIParseException("values array must be non-null and contain " + ELEMENT_COUNT + " elements");
		}
		C024_01 = EDIUtils.getStringValue(values, 0, 2, 3, true);
		String overrideKey0 = ordinal + "-" + 60;
		Object[] lvalues0 = (Object[]) Field1362.getLegalValues(overrideKey0);
		if (!EDIUtils.validateValue(C024_01, lvalues0)) {
			throw new EDIParseException("Illegal value '" + C024_01 + "' for field C024_01");
		}
		if (C024_01 == null) {
			throw new EDIParseException("Field 'C024_01' is mandatory");
		}
		C024_02 = EDIUtils.getStringValue(values, 1, 2, 3, false);
		String overrideKey1 = ordinal + "-" + 61;
		Object[] lvalues1 = (Object[]) Field1362.getLegalValues(overrideKey1);
		if (!EDIUtils.validateValue(C024_02, lvalues1)) {
			throw new EDIParseException("Illegal value '" + C024_02 + "' for field C024_02");
		}
		C024_03 = EDIUtils.getStringValue(values, 2, 2, 3, false);
		String overrideKey2 = ordinal + "-" + 62;
		Object[] lvalues2 = (Object[]) Field1362.getLegalValues(overrideKey2);
		if (!EDIUtils.validateValue(C024_03, lvalues2)) {
			throw new EDIParseException("Illegal value '" + C024_03 + "' for field C024_03");
		}
		C024_04 = EDIUtils.getStringValue(values, 3, 2, 2, false);
		C024_05 = EDIUtils.getStringValue(values, 4, 2, 3, false);
	}

	public void parse(EDIInputStream eis, String fieldValue) throws IOException {
		String[] elements = eis.getCompositeValue(fieldValue, ELEMENT_COUNT);
		C024_01 = eis.getStringValue(elements, 0, 2, 3, true);
		Field1362.validateInputValue(eis, "C024_01", C024_01, ordinal, 60);
		if (C024_01 == null) {
			eis.addError("Field 'C024_01' is mandatory");
		}
		C024_02 = eis.getStringValue(elements, 1, 2, 3, false);
		Field1362.validateInputValue(eis, "C024_02", C024_02, ordinal, 61);
		C024_03 = eis.getStringValue(elements, 2, 2, 3, false);
		Field1362.validateInputValue(eis, "C024_03", C024_03, ordinal, 62);
		C024_04 = eis.getStringValue(elements, 3, 2, 2, false);
		C024_05 = eis.getStringValue(elements, 4, 2, 3, false);
	}

	public void emit(EDIOutputStream eos) throws IOException {
		eos.startComposite();
		if (C024_01 == null) {
			eos.addError("Emitting null mandatory field 'C024_01'");
		}
		eos.writeElement(C024_01);
		eos.writeElement(C024_02);
		eos.writeElement(C024_03);
		eos.writeElement(C024_04);
		eos.writeElement(C024_05);
		eos.endComposite();
	}

	public EDIElement createCopy() {
		CompositeC024_1 copy = new CompositeC024_1();
		copy.C024_01 = this.C024_01;
		copy.C024_02 = this.C024_02;
		copy.C024_03 = this.C024_03;
		copy.C024_04 = this.C024_04;
		copy.C024_05 = this.C024_05;
		return copy;
	}
}
