package com.webify.shared.edi.model.hipaa837p.beans;

import com.webify.shared.edi.model.*;
import java.io.IOException;

/*
 * AUTOGENERATED FILE - DO NOT EDIT!!!
 */
public class CompositeC004_1 implements EDICompositeField {

	public static final String COMPOSITE_NAME = "C004";
	public static final int ELEMENT_COUNT = 4;

	private String ordinal = null;
	void setOrdinal(String ord) { ordinal = ord; }

	// Elements
	private Integer C004_01;
	public Integer getC004_01() { return C004_01; }
	public void setC004_01(Integer val) { C004_01 = val; }

	private Integer C004_02;
	public Integer getC004_02() { return C004_02; }
	public void setC004_02(Integer val) { C004_02 = val; }

	private Integer C004_03;
	public Integer getC004_03() { return C004_03; }
	public void setC004_03(Integer val) { C004_03 = val; }

	private Integer C004_04;
	public Integer getC004_04() { return C004_04; }
	public void setC004_04(Integer val) { C004_04 = val; }

	public String[] getElements() {
		String[] values = new String[ELEMENT_COUNT];
		values[0] = EDIUtils.stringValue(C004_01);
		values[1] = EDIUtils.stringValue(C004_02);
		values[2] = EDIUtils.stringValue(C004_03);
		values[3] = EDIUtils.stringValue(C004_04);
		return values;
	}

	public void setElements(String[] values) throws EDIParseException {
		if (values == null || values.length != ELEMENT_COUNT) {
			throw new EDIParseException("values array must be non-null and contain " + ELEMENT_COUNT + " elements");
		}
		C004_01 = EDIUtils.getIntegerValue(values, 0, true);
		if (C004_01 == null) {
			throw new EDIParseException("Field 'C004_01' is mandatory");
		}
		C004_02 = EDIUtils.getIntegerValue(values, 1, false);
		C004_03 = EDIUtils.getIntegerValue(values, 2, false);
		C004_04 = EDIUtils.getIntegerValue(values, 3, false);
	}

	public void parse(EDIInputStream eis, String fieldValue) throws IOException {
		String[] elements = eis.getCompositeValue(fieldValue, ELEMENT_COUNT);
		C004_01 = eis.getIntegerValue(elements, 0, true);
		if (C004_01 == null) {
			eis.addError("Field 'C004_01' is mandatory");
		}
		C004_02 = eis.getIntegerValue(elements, 1, false);
		C004_03 = eis.getIntegerValue(elements, 2, false);
		C004_04 = eis.getIntegerValue(elements, 3, false);
	}

	public void emit(EDIOutputStream eos) throws IOException {
		eos.startComposite();
		if (C004_01 == null) {
			eos.addError("Emitting null mandatory field 'C004_01'");
		}
		eos.writeElement(C004_01);
		eos.writeElement(C004_02);
		eos.writeElement(C004_03);
		eos.writeElement(C004_04);
		eos.endComposite();
	}

	public EDIElement createCopy() {
		CompositeC004_1 copy = new CompositeC004_1();
		copy.C004_01 = this.C004_01;
		copy.C004_02 = this.C004_02;
		copy.C004_03 = this.C004_03;
		copy.C004_04 = this.C004_04;
		return copy;
	}
}
