package com.webify.shared.edi.model.hipaa837p.beans;

import java.util.*;
import com.webify.shared.edi.model.*;

/*
 * AUTOGENERATED FILE - DO NOT EDIT!!!
 */
public class Field640 {

	private static final Object[] DEFAULT_LEGAL_VALUES = new Object[167];
	private static final Map valueOverrides = new HashMap();

	static {
		DEFAULT_LEGAL_VALUES[0] = new String[] { "01", "11" };
		DEFAULT_LEGAL_VALUES[1] = new String[] { "13", "30" };
		DEFAULT_LEGAL_VALUES[2] = new String[] { "33", "41" };
		DEFAULT_LEGAL_VALUES[3] = "60";
		DEFAULT_LEGAL_VALUES[4] = new String[] { "62", "83" };
		DEFAULT_LEGAL_VALUES[5] = "85";
		DEFAULT_LEGAL_VALUES[6] = "87";
		DEFAULT_LEGAL_VALUES[7] = "88";
		DEFAULT_LEGAL_VALUES[8] = "91";
		DEFAULT_LEGAL_VALUES[9] = "94";
		DEFAULT_LEGAL_VALUES[10] = "95";
		DEFAULT_LEGAL_VALUES[11] = new String[] { "97", "99" };
		DEFAULT_LEGAL_VALUES[12] = "3M";
		DEFAULT_LEGAL_VALUES[13] = "6A";
		DEFAULT_LEGAL_VALUES[14] = "6C";
		DEFAULT_LEGAL_VALUES[15] = "6N";
		DEFAULT_LEGAL_VALUES[16] = "6R";
		DEFAULT_LEGAL_VALUES[17] = "6S";
		DEFAULT_LEGAL_VALUES[18] = "A0";
		DEFAULT_LEGAL_VALUES[19] = "A1";
		DEFAULT_LEGAL_VALUES[20] = new String[] { "A3", "A7" };
		DEFAULT_LEGAL_VALUES[21] = new String[] { "AA", "AG" };
		DEFAULT_LEGAL_VALUES[22] = "AI";
		DEFAULT_LEGAL_VALUES[23] = "AM";
		DEFAULT_LEGAL_VALUES[24] = "AN";
		DEFAULT_LEGAL_VALUES[25] = new String[] { "AP", "AT" };
		DEFAULT_LEGAL_VALUES[26] = "AV";
		DEFAULT_LEGAL_VALUES[27] = "AW";
		DEFAULT_LEGAL_VALUES[28] = new String[] { "AZ", "BB" };
		DEFAULT_LEGAL_VALUES[29] = "BD";
		DEFAULT_LEGAL_VALUES[30] = "BF";
		DEFAULT_LEGAL_VALUES[31] = "BH";
		DEFAULT_LEGAL_VALUES[32] = new String[] { "BJ", "BP" };
		DEFAULT_LEGAL_VALUES[33] = new String[] { "BR", "BW" };
		DEFAULT_LEGAL_VALUES[34] = new String[] { "C0", "C3" };
		DEFAULT_LEGAL_VALUES[35] = new String[] { "CA", "CP" };
		DEFAULT_LEGAL_VALUES[36] = new String[] { "CR", "CZ" };
		DEFAULT_LEGAL_VALUES[37] = "D1";
		DEFAULT_LEGAL_VALUES[38] = "D4";
		DEFAULT_LEGAL_VALUES[39] = new String[] { "DA", "DI" };
		DEFAULT_LEGAL_VALUES[40] = "DK";
		DEFAULT_LEGAL_VALUES[41] = "DL";
		DEFAULT_LEGAL_VALUES[42] = new String[] { "DN", "DU" };
		DEFAULT_LEGAL_VALUES[43] = "EA";
		DEFAULT_LEGAL_VALUES[44] = "EB";
		DEFAULT_LEGAL_VALUES[45] = "EF";
		DEFAULT_LEGAL_VALUES[46] = "EI";
		DEFAULT_LEGAL_VALUES[47] = "EM";
		DEFAULT_LEGAL_VALUES[48] = "EP";
		DEFAULT_LEGAL_VALUES[49] = "ER";
		DEFAULT_LEGAL_VALUES[50] = "EX";
		DEFAULT_LEGAL_VALUES[51] = new String[] { "FA", "FG" };
		DEFAULT_LEGAL_VALUES[52] = "FI";
		DEFAULT_LEGAL_VALUES[53] = new String[] { "FL", "FN" };
		DEFAULT_LEGAL_VALUES[54] = "FP";
		DEFAULT_LEGAL_VALUES[55] = new String[] { "FR", "FT" };
		DEFAULT_LEGAL_VALUES[56] = "GA";
		DEFAULT_LEGAL_VALUES[57] = "GI";
		DEFAULT_LEGAL_VALUES[58] = "GR";
		DEFAULT_LEGAL_VALUES[59] = "HP";
		DEFAULT_LEGAL_VALUES[60] = "I1";
		DEFAULT_LEGAL_VALUES[61] = new String[] { "IA", "IF" };
		DEFAULT_LEGAL_VALUES[62] = "II";
		DEFAULT_LEGAL_VALUES[63] = new String[] { "IM", "IO" };
		DEFAULT_LEGAL_VALUES[64] = "IR";
		DEFAULT_LEGAL_VALUES[65] = "IU";
		DEFAULT_LEGAL_VALUES[66] = "IW";
		DEFAULT_LEGAL_VALUES[67] = "IX";
		DEFAULT_LEGAL_VALUES[68] = "IZ";
		DEFAULT_LEGAL_VALUES[69] = "JM";
		DEFAULT_LEGAL_VALUES[70] = "JO";
		DEFAULT_LEGAL_VALUES[71] = "JR";
		DEFAULT_LEGAL_VALUES[72] = "JS";
		DEFAULT_LEGAL_VALUES[73] = "JU";
		DEFAULT_LEGAL_VALUES[74] = "JX";
		DEFAULT_LEGAL_VALUES[75] = new String[] { "KB", "KN" };
		DEFAULT_LEGAL_VALUES[76] = "KS";
		DEFAULT_LEGAL_VALUES[77] = "KT";
		DEFAULT_LEGAL_VALUES[78] = new String[] { "LC", "LF" };
		DEFAULT_LEGAL_VALUES[79] = new String[] { "LN", "LP" };
		DEFAULT_LEGAL_VALUES[80] = "LR";
		DEFAULT_LEGAL_VALUES[81] = "LV";
		DEFAULT_LEGAL_VALUES[82] = "M1";
		DEFAULT_LEGAL_VALUES[83] = new String[] { "MA", "MF" };
		DEFAULT_LEGAL_VALUES[84] = "MI";
		DEFAULT_LEGAL_VALUES[85] = "ML";
		DEFAULT_LEGAL_VALUES[86] = "MM";
		DEFAULT_LEGAL_VALUES[87] = "MP";
		DEFAULT_LEGAL_VALUES[88] = "MR";
		DEFAULT_LEGAL_VALUES[89] = "MS";
		DEFAULT_LEGAL_VALUES[90] = "MU";
		DEFAULT_LEGAL_VALUES[91] = new String[] { "N1", "N8" };
		DEFAULT_LEGAL_VALUES[92] = new String[] { "NA", "NM" };
		DEFAULT_LEGAL_VALUES[93] = new String[] { "NO", "NR" };
		DEFAULT_LEGAL_VALUES[94] = "NT";
		DEFAULT_LEGAL_VALUES[95] = "NU";
		DEFAULT_LEGAL_VALUES[96] = "OC";
		DEFAULT_LEGAL_VALUES[97] = "OF";
		DEFAULT_LEGAL_VALUES[98] = "OP";
		DEFAULT_LEGAL_VALUES[99] = "OR";
		DEFAULT_LEGAL_VALUES[100] = "P1";
		DEFAULT_LEGAL_VALUES[101] = new String[] { "PA", "PG" };
		DEFAULT_LEGAL_VALUES[102] = "PI";
		DEFAULT_LEGAL_VALUES[103] = "PL";
		DEFAULT_LEGAL_VALUES[104] = "PM";
		DEFAULT_LEGAL_VALUES[105] = "PO";
		DEFAULT_LEGAL_VALUES[106] = "PP";
		DEFAULT_LEGAL_VALUES[107] = new String[] { "PR", "PX" };
		DEFAULT_LEGAL_VALUES[108] = new String[] { "PZ", "QH" };
		DEFAULT_LEGAL_VALUES[109] = new String[] { "QJ", "QL" };
		DEFAULT_LEGAL_VALUES[110] = "QP";
		DEFAULT_LEGAL_VALUES[111] = "QR";
		DEFAULT_LEGAL_VALUES[112] = new String[] { "R1", "R8" };
		DEFAULT_LEGAL_VALUES[113] = new String[] { "RA", "RH" };
		DEFAULT_LEGAL_VALUES[114] = "RK";
		DEFAULT_LEGAL_VALUES[115] = "RM";
		DEFAULT_LEGAL_VALUES[116] = "RP";
		DEFAULT_LEGAL_VALUES[117] = "RQ";
		DEFAULT_LEGAL_VALUES[118] = new String[] { "RS", "RU" };
		DEFAULT_LEGAL_VALUES[119] = "RZ";
		DEFAULT_LEGAL_VALUES[120] = new String[] { "S1", "S4" };
		DEFAULT_LEGAL_VALUES[121] = new String[] { "SA", "SH" };
		DEFAULT_LEGAL_VALUES[122] = "SL";
		DEFAULT_LEGAL_VALUES[123] = "SM";
		DEFAULT_LEGAL_VALUES[124] = new String[] { "SO", "SV" };
		DEFAULT_LEGAL_VALUES[125] = "TD";
		DEFAULT_LEGAL_VALUES[126] = new String[] { "TG", "TK" };
		DEFAULT_LEGAL_VALUES[127] = "TP";
		DEFAULT_LEGAL_VALUES[128] = new String[] { "TR", "TT" };
		DEFAULT_LEGAL_VALUES[129] = "TX";
		DEFAULT_LEGAL_VALUES[130] = "U1";
		DEFAULT_LEGAL_VALUES[131] = "U2";
		DEFAULT_LEGAL_VALUES[132] = "U4";
		DEFAULT_LEGAL_VALUES[133] = "U5";
		DEFAULT_LEGAL_VALUES[134] = "U9";
		DEFAULT_LEGAL_VALUES[135] = "UA";
		DEFAULT_LEGAL_VALUES[136] = "UC";
		DEFAULT_LEGAL_VALUES[137] = "UD";
		DEFAULT_LEGAL_VALUES[138] = "UF";
		DEFAULT_LEGAL_VALUES[139] = "UI";
		DEFAULT_LEGAL_VALUES[140] = "UM";
		DEFAULT_LEGAL_VALUES[141] = "UO";
		DEFAULT_LEGAL_VALUES[142] = "UP";
		DEFAULT_LEGAL_VALUES[143] = "UR";
		DEFAULT_LEGAL_VALUES[144] = "UT";
		DEFAULT_LEGAL_VALUES[145] = "V1";
		DEFAULT_LEGAL_VALUES[146] = "VH";
		DEFAULT_LEGAL_VALUES[147] = "VJ";
		DEFAULT_LEGAL_VALUES[148] = new String[] { "VL", "VR" };
		DEFAULT_LEGAL_VALUES[149] = "W1";
		DEFAULT_LEGAL_VALUES[150] = "W4";
		DEFAULT_LEGAL_VALUES[151] = "W5";
		DEFAULT_LEGAL_VALUES[152] = "WA";
		DEFAULT_LEGAL_VALUES[153] = "WC";
		DEFAULT_LEGAL_VALUES[154] = "WD";
		DEFAULT_LEGAL_VALUES[155] = "WH";
		DEFAULT_LEGAL_VALUES[156] = "WO";
		DEFAULT_LEGAL_VALUES[157] = "WS";
		DEFAULT_LEGAL_VALUES[158] = "WT";
		DEFAULT_LEGAL_VALUES[159] = "X1";
		DEFAULT_LEGAL_VALUES[160] = new String[] { "XA", "XD" };
		DEFAULT_LEGAL_VALUES[161] = new String[] { "XX", "XZ" };
		DEFAULT_LEGAL_VALUES[162] = "YI";
		DEFAULT_LEGAL_VALUES[163] = "YR";
		DEFAULT_LEGAL_VALUES[164] = new String[] { "ZA", "ZU" };
		DEFAULT_LEGAL_VALUES[165] = "ZW";
		DEFAULT_LEGAL_VALUES[166] = "ZZ";
		createOverrides();
	}

	public static Object[] getLegalValues(String overrideKey) {
		Object[] currentValues = (Object[]) valueOverrides.get(overrideKey);
		if (currentValues == null) {
			return DEFAULT_LEGAL_VALUES;
		}
		return currentValues;
	}

	private static void createOverrides() {
		Object[] currentValues = null;

		currentValues = new Object[2];
		currentValues[0] = "CH";
		currentValues[1] = "RP";
		valueOverrides.put("2-6", currentValues);
	}

	public static boolean validateValue(String value) {
		return EDIUtils.validateValue(value, DEFAULT_LEGAL_VALUES);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, int segmentOrdinal, int fieldOrdinal) {
		String overrideKey = segmentOrdinal + "-" + fieldOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, String compositeOrdinal, int elementOrdinal) {
		String overrideKey = compositeOrdinal + "-" + elementOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}
}
