package com.webify.shared.edi.model.hipaa837p.beans;

import java.util.*;
import com.webify.shared.edi.model.*;

/*
 * AUTOGENERATED FILE - DO NOT EDIT!!!
 */
public class Field1250 {

	private static final Object[] DEFAULT_LEGAL_VALUES = new Object[33];
	private static final Map valueOverrides = new HashMap();

	static {
		DEFAULT_LEGAL_VALUES[0] = "CC";
		DEFAULT_LEGAL_VALUES[1] = "CD";
		DEFAULT_LEGAL_VALUES[2] = "CM";
		DEFAULT_LEGAL_VALUES[3] = "CQ";
		DEFAULT_LEGAL_VALUES[4] = "CY";
		DEFAULT_LEGAL_VALUES[5] = "D6";
		DEFAULT_LEGAL_VALUES[6] = "D8";
		DEFAULT_LEGAL_VALUES[7] = "DA";
		DEFAULT_LEGAL_VALUES[8] = "DB";
		DEFAULT_LEGAL_VALUES[9] = "DD";
		DEFAULT_LEGAL_VALUES[10] = "DT";
		DEFAULT_LEGAL_VALUES[11] = "DTS";
		DEFAULT_LEGAL_VALUES[12] = "EH";
		DEFAULT_LEGAL_VALUES[13] = "KA";
		DEFAULT_LEGAL_VALUES[14] = "MD";
		DEFAULT_LEGAL_VALUES[15] = "MM";
		DEFAULT_LEGAL_VALUES[16] = "RD";
		DEFAULT_LEGAL_VALUES[17] = "RD2";
		DEFAULT_LEGAL_VALUES[18] = new String[] { "RD4", "RD6" };
		DEFAULT_LEGAL_VALUES[19] = "RD8";
		DEFAULT_LEGAL_VALUES[20] = "RDM";
		DEFAULT_LEGAL_VALUES[21] = "RDT";
		DEFAULT_LEGAL_VALUES[22] = "RMD";
		DEFAULT_LEGAL_VALUES[23] = "RMY";
		DEFAULT_LEGAL_VALUES[24] = "RTM";
		DEFAULT_LEGAL_VALUES[25] = "RTS";
		DEFAULT_LEGAL_VALUES[26] = "TC";
		DEFAULT_LEGAL_VALUES[27] = "TM";
		DEFAULT_LEGAL_VALUES[28] = new String[] { "TQ", "TU" };
		DEFAULT_LEGAL_VALUES[29] = "UN";
		DEFAULT_LEGAL_VALUES[30] = "YM";
		DEFAULT_LEGAL_VALUES[31] = "YMM";
		DEFAULT_LEGAL_VALUES[32] = "YY";
		createOverrides();
	}

	public static Object[] getLegalValues(String overrideKey) {
		Object[] currentValues = (Object[]) valueOverrides.get(overrideKey);
		if (currentValues == null) {
			return DEFAULT_LEGAL_VALUES;
		}
		return currentValues;
	}

	private static void createOverrides() {
		Object[] currentValues = null;

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("360-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("175-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("251-2", currentValues);

		currentValues = new Object[2];
		currentValues[0] = "D8";
		currentValues[1] = "DT";
		valueOverrides.put("248-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("166-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("249-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("259-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("237-1", currentValues);

		currentValues = new Object[2];
		currentValues[0] = "D8";
		currentValues[1] = "RD8";
		valueOverrides.put("163-2", currentValues);

		currentValues = new Object[2];
		currentValues[0] = "D8";
		currentValues[1] = "RD8";
		valueOverrides.put("357-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("57-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("366-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("246-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("247-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("174-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("169-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("365-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("177-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("245-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("47-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("250-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("61-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("172-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("359-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("369-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("371-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("125-1", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("252-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("173-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("171-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("167-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("51-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("330-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("176-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("370-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("228-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("257-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("319-1", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("243-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("53-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("50-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("254-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("65-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("164-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("368-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("358-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("363-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("422-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("253-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("136-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("62-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("256-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("232-5", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("63-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("48-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("170-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("58-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("361-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("55-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("59-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("242-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("362-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("26-5", currentValues);

		currentValues = new Object[2];
		currentValues[0] = "D8";
		currentValues[1] = "DT";
		valueOverrides.put("54-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("60-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("258-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("52-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("31-1", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("165-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("244-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("168-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("49-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("56-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("255-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("367-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("241-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("364-2", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "D8";
		valueOverrides.put("64-2", currentValues);
	}

	public static boolean validateValue(String value) {
		return EDIUtils.validateValue(value, DEFAULT_LEGAL_VALUES);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, int segmentOrdinal, int fieldOrdinal) {
		String overrideKey = segmentOrdinal + "-" + fieldOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, String compositeOrdinal, int elementOrdinal) {
		String overrideKey = compositeOrdinal + "-" + elementOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}
}
