package com.webify.shared.edi.model.hipaa837p.beans;

import java.util.*;
import com.webify.shared.edi.model.*;

/*
 * AUTOGENERATED FILE - DO NOT EDIT!!!
 */
public class Field755 {

	private static final Object[] DEFAULT_LEGAL_VALUES = new Object[112];
	private static final Map valueOverrides = new HashMap();

	static {
		DEFAULT_LEGAL_VALUES[0] = new String[] { "01", "97" };
		DEFAULT_LEGAL_VALUES[1] = new String[] { "A1", "A4" };
		DEFAULT_LEGAL_VALUES[2] = new String[] { "AA", "AZ" };
		DEFAULT_LEGAL_VALUES[3] = new String[] { "B1", "B4" };
		DEFAULT_LEGAL_VALUES[4] = new String[] { "BA", "BC" };
		DEFAULT_LEGAL_VALUES[5] = "BE";
		DEFAULT_LEGAL_VALUES[6] = "BF";
		DEFAULT_LEGAL_VALUES[7] = new String[] { "BL", "BO" };
		DEFAULT_LEGAL_VALUES[8] = new String[] { "BR", "BT" };
		DEFAULT_LEGAL_VALUES[9] = "BW";
		DEFAULT_LEGAL_VALUES[10] = "BY";
		DEFAULT_LEGAL_VALUES[11] = new String[] { "C1", "C9" };
		DEFAULT_LEGAL_VALUES[12] = new String[] { "CA", "CU" };
		DEFAULT_LEGAL_VALUES[13] = new String[] { "CW", "CZ" };
		DEFAULT_LEGAL_VALUES[14] = "D2";
		DEFAULT_LEGAL_VALUES[15] = new String[] { "DA", "DN" };
		DEFAULT_LEGAL_VALUES[16] = new String[] { "DQ", "DW" };
		DEFAULT_LEGAL_VALUES[17] = "E1";
		DEFAULT_LEGAL_VALUES[18] = new String[] { "EA", "ED" };
		DEFAULT_LEGAL_VALUES[19] = "EL";
		DEFAULT_LEGAL_VALUES[20] = "EP";
		DEFAULT_LEGAL_VALUES[21] = "ER";
		DEFAULT_LEGAL_VALUES[22] = "EX";
		DEFAULT_LEGAL_VALUES[23] = "EY";
		DEFAULT_LEGAL_VALUES[24] = new String[] { "F1", "F9" };
		DEFAULT_LEGAL_VALUES[25] = new String[] { "FB", "FE" };
		DEFAULT_LEGAL_VALUES[26] = "FH";
		DEFAULT_LEGAL_VALUES[27] = "FI";
		DEFAULT_LEGAL_VALUES[28] = "FM";
		DEFAULT_LEGAL_VALUES[29] = "FS";
		DEFAULT_LEGAL_VALUES[30] = "GP";
		DEFAULT_LEGAL_VALUES[31] = "GT";
		DEFAULT_LEGAL_VALUES[32] = "HC";
		DEFAULT_LEGAL_VALUES[33] = "HR";
		DEFAULT_LEGAL_VALUES[34] = "HW";
		DEFAULT_LEGAL_VALUES[35] = new String[] { "I2", "I6" };
		DEFAULT_LEGAL_VALUES[36] = "IA";
		DEFAULT_LEGAL_VALUES[37] = "IC";
		DEFAULT_LEGAL_VALUES[38] = "IM";
		DEFAULT_LEGAL_VALUES[39] = "IN";
		DEFAULT_LEGAL_VALUES[40] = "IP";
		DEFAULT_LEGAL_VALUES[41] = new String[] { "IR", "IV" };
		DEFAULT_LEGAL_VALUES[42] = new String[] { "JA", "JI" };
		DEFAULT_LEGAL_VALUES[43] = new String[] { "JK", "JT" };
		DEFAULT_LEGAL_VALUES[44] = new String[] { "JV", "KA" };
		DEFAULT_LEGAL_VALUES[45] = new String[] { "KC", "KJ" };
		DEFAULT_LEGAL_VALUES[46] = new String[] { "KY", "LE" };
		DEFAULT_LEGAL_VALUES[47] = "LG";
		DEFAULT_LEGAL_VALUES[48] = "LI";
		DEFAULT_LEGAL_VALUES[49] = "LO";
		DEFAULT_LEGAL_VALUES[50] = "LP";
		DEFAULT_LEGAL_VALUES[51] = new String[] { "LR", "LT" };
		DEFAULT_LEGAL_VALUES[52] = "LW";
		DEFAULT_LEGAL_VALUES[53] = "M1";
		DEFAULT_LEGAL_VALUES[54] = new String[] { "MA", "MT" };
		DEFAULT_LEGAL_VALUES[55] = "MV";
		DEFAULT_LEGAL_VALUES[56] = "MZ";
		DEFAULT_LEGAL_VALUES[57] = "NA";
		DEFAULT_LEGAL_VALUES[58] = "NC";
		DEFAULT_LEGAL_VALUES[59] = "ND";
		DEFAULT_LEGAL_VALUES[60] = "NI";
		DEFAULT_LEGAL_VALUES[61] = new String[] { "NL", "NO" };
		DEFAULT_LEGAL_VALUES[62] = "NQ";
		DEFAULT_LEGAL_VALUES[63] = "NR";
		DEFAULT_LEGAL_VALUES[64] = "NT";
		DEFAULT_LEGAL_VALUES[65] = new String[] { "OB", "OE" };
		DEFAULT_LEGAL_VALUES[66] = "OL";
		DEFAULT_LEGAL_VALUES[67] = "OP";
		DEFAULT_LEGAL_VALUES[68] = new String[] { "OR", "OT" };
		DEFAULT_LEGAL_VALUES[69] = "OX";
		DEFAULT_LEGAL_VALUES[70] = "OZ";
		DEFAULT_LEGAL_VALUES[71] = new String[] { "P1", "P8" };
		DEFAULT_LEGAL_VALUES[72] = new String[] { "PA", "PT" };
		DEFAULT_LEGAL_VALUES[73] = new String[] { "PV", "PZ" };
		DEFAULT_LEGAL_VALUES[74] = new String[] { "QC", "QE" };
		DEFAULT_LEGAL_VALUES[75] = "QM";
		DEFAULT_LEGAL_VALUES[76] = new String[] { "QR", "QT" };
		DEFAULT_LEGAL_VALUES[77] = new String[] { "R1", "R6" };
		DEFAULT_LEGAL_VALUES[78] = new String[] { "RA", "RG" };
		DEFAULT_LEGAL_VALUES[79] = new String[] { "RM", "RO" };
		DEFAULT_LEGAL_VALUES[80] = "RR";
		DEFAULT_LEGAL_VALUES[81] = "RT";
		DEFAULT_LEGAL_VALUES[82] = "RV";
		DEFAULT_LEGAL_VALUES[83] = "RX";
		DEFAULT_LEGAL_VALUES[84] = new String[] { "S1", "S9" };
		DEFAULT_LEGAL_VALUES[85] = new String[] { "SA", "SI" };
		DEFAULT_LEGAL_VALUES[86] = new String[] { "SL", "SY" };
		DEFAULT_LEGAL_VALUES[87] = new String[] { "T1", "T6" };
		DEFAULT_LEGAL_VALUES[88] = new String[] { "TA", "TT" };
		DEFAULT_LEGAL_VALUES[89] = "TX";
		DEFAULT_LEGAL_VALUES[90] = "U1";
		DEFAULT_LEGAL_VALUES[91] = "UA";
		DEFAULT_LEGAL_VALUES[92] = "UB";
		DEFAULT_LEGAL_VALUES[93] = new String[] { "UD", "UV" };
		DEFAULT_LEGAL_VALUES[94] = new String[] { "UX", "UZ" };
		DEFAULT_LEGAL_VALUES[95] = new String[] { "V1", "V7" };
		DEFAULT_LEGAL_VALUES[96] = "VA";
		DEFAULT_LEGAL_VALUES[97] = "VC";
		DEFAULT_LEGAL_VALUES[98] = "VD";
		DEFAULT_LEGAL_VALUES[99] = "VM";
		DEFAULT_LEGAL_VALUES[100] = "W1";
		DEFAULT_LEGAL_VALUES[101] = "W2";
		DEFAULT_LEGAL_VALUES[102] = new String[] { "WA", "WI" };
		DEFAULT_LEGAL_VALUES[103] = "WP";
		DEFAULT_LEGAL_VALUES[104] = "WT";
		DEFAULT_LEGAL_VALUES[105] = new String[] { "X1", "X5" };
		DEFAULT_LEGAL_VALUES[106] = "XE";
		DEFAULT_LEGAL_VALUES[107] = "XP";
		DEFAULT_LEGAL_VALUES[108] = new String[] { "Y1", "Y3" };
		DEFAULT_LEGAL_VALUES[109] = "ZA";
		DEFAULT_LEGAL_VALUES[110] = "ZB";
		DEFAULT_LEGAL_VALUES[111] = "ZZ";
		createOverrides();
	}

	public static Object[] getLegalValues(String overrideKey) {
		Object[] currentValues = (Object[]) valueOverrides.get(overrideKey);
		if (currentValues == null) {
			return DEFAULT_LEGAL_VALUES;
		}
		return currentValues;
	}

	private static void createOverrides() {
		Object[] currentValues = null;

		currentValues = new Object[18];
		currentValues[0] = "77";
		currentValues[1] = "AS";
		currentValues[2] = new String[] { "B2", "B4" };
		currentValues[3] = "CT";
		currentValues[4] = "DA";
		currentValues[5] = "DG";
		currentValues[6] = "DS";
		currentValues[7] = "EB";
		currentValues[8] = "MT";
		currentValues[9] = "NN";
		currentValues[10] = "OB";
		currentValues[11] = "OZ";
		currentValues[12] = "PN";
		currentValues[13] = "PO";
		currentValues[14] = "PZ";
		currentValues[15] = "RB";
		currentValues[16] = "RR";
		currentValues[17] = "RT";
		valueOverrides.put("66-1", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "CT";
		valueOverrides.put("349-1", currentValues);

		currentValues = new Object[18];
		currentValues[0] = "77";
		currentValues[1] = "AS";
		currentValues[2] = new String[] { "B2", "B4" };
		currentValues[3] = "CT";
		currentValues[4] = "DA";
		currentValues[5] = "DG";
		currentValues[6] = "DS";
		currentValues[7] = "EB";
		currentValues[8] = "MT";
		currentValues[9] = "NN";
		currentValues[10] = "OB";
		currentValues[11] = "OZ";
		currentValues[12] = "PN";
		currentValues[13] = "PO";
		currentValues[14] = "PZ";
		currentValues[15] = "RB";
		currentValues[16] = "RR";
		currentValues[17] = "RT";
		valueOverrides.put("260-1", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "CT";
		valueOverrides.put("155-1", currentValues);
	}

	public static boolean validateValue(String value) {
		return EDIUtils.validateValue(value, DEFAULT_LEGAL_VALUES);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, int segmentOrdinal, int fieldOrdinal) {
		String overrideKey = segmentOrdinal + "-" + fieldOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, String compositeOrdinal, int elementOrdinal) {
		String overrideKey = compositeOrdinal + "-" + elementOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}
}
