package com.webify.shared.edi.model.hipaa270.beans;

import java.util.*;
import com.webify.shared.edi.model.*;

/*
 * AUTOGENERATED FILE - DO NOT EDIT!!!
 */
public class Field1365 {

	private static final Object[] DEFAULT_LEGAL_VALUES = new Object[9];
	private static final Map valueOverrides = new HashMap();

	static {
		DEFAULT_LEGAL_VALUES[0] = new String[] { "1", "9" };
		DEFAULT_LEGAL_VALUES[1] = new String[] { "10", "28" };
		DEFAULT_LEGAL_VALUES[2] = new String[] { "30", "99" };
		DEFAULT_LEGAL_VALUES[3] = new String[] { "A0", "A9" };
		DEFAULT_LEGAL_VALUES[4] = new String[] { "AA", "AO" };
		DEFAULT_LEGAL_VALUES[5] = "AQ";
		DEFAULT_LEGAL_VALUES[6] = "AR";
		DEFAULT_LEGAL_VALUES[7] = new String[] { "BA", "BN" };
		DEFAULT_LEGAL_VALUES[8] = new String[] { "BP", "BS" };
		createOverrides();
	}

	public static Object[] getLegalValues(String overrideKey) {
		Object[] currentValues = (Object[]) valueOverrides.get(overrideKey);
		if (currentValues == null) {
			return DEFAULT_LEGAL_VALUES;
		}
		return currentValues;
	}

	private static void createOverrides() {
		Object[] currentValues = null;

		currentValues = new Object[10];
		currentValues[0] = new String[] { "1", "9" };
		currentValues[1] = new String[] { "10", "28" };
		currentValues[2] = "30";
		currentValues[3] = new String[] { "32", "99" };
		currentValues[4] = new String[] { "A0", "A9" };
		currentValues[5] = new String[] { "AA", "AO" };
		currentValues[6] = "AQ";
		currentValues[7] = "AR";
		currentValues[8] = new String[] { "BA", "BN" };
		currentValues[9] = new String[] { "BP", "BS" };
		valueOverrides.put("37-1", currentValues);

		currentValues = new Object[10];
		currentValues[0] = new String[] { "1", "9" };
		currentValues[1] = new String[] { "10", "28" };
		currentValues[2] = "30";
		currentValues[3] = new String[] { "32", "99" };
		currentValues[4] = new String[] { "A0", "A9" };
		currentValues[5] = new String[] { "AA", "AO" };
		currentValues[6] = "AQ";
		currentValues[7] = "AR";
		currentValues[8] = new String[] { "BA", "BN" };
		currentValues[9] = new String[] { "BP", "BS" };
		valueOverrides.put("22-1", currentValues);
	}

	public static boolean validateValue(String value) {
		return EDIUtils.validateValue(value, DEFAULT_LEGAL_VALUES);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, int segmentOrdinal, int fieldOrdinal) {
		String overrideKey = segmentOrdinal + "-" + fieldOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, String compositeOrdinal, int elementOrdinal) {
		String overrideKey = compositeOrdinal + "-" + elementOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}
}
