package com.webify.shared.edi.model.hipaa277.beans;

import java.util.*;
import com.webify.shared.edi.model.*;

/*
 * AUTOGENERATED FILE - DO NOT EDIT!!!
 */
public class Field374 {

	private static final Object[] DEFAULT_LEGAL_VALUES = new Object[136];
	private static final Map valueOverrides = new HashMap();

	static {
		DEFAULT_LEGAL_VALUES[0] = new String[] { "001", "116" };
		DEFAULT_LEGAL_VALUES[1] = new String[] { "118", "122" };
		DEFAULT_LEGAL_VALUES[2] = new String[] { "124", "406" };
		DEFAULT_LEGAL_VALUES[3] = new String[] { "408", "587" };
		DEFAULT_LEGAL_VALUES[4] = new String[] { "589", "604" };
		DEFAULT_LEGAL_VALUES[5] = new String[] { "606", "627" };
		DEFAULT_LEGAL_VALUES[6] = new String[] { "629", "638" };
		DEFAULT_LEGAL_VALUES[7] = new String[] { "640", "644" };
		DEFAULT_LEGAL_VALUES[8] = new String[] { "646", "653" };
		DEFAULT_LEGAL_VALUES[9] = new String[] { "655", "675" };
		DEFAULT_LEGAL_VALUES[10] = new String[] { "681", "697" };
		DEFAULT_LEGAL_VALUES[11] = new String[] { "699", "734" };
		DEFAULT_LEGAL_VALUES[12] = new String[] { "736", "746" };
		DEFAULT_LEGAL_VALUES[13] = new String[] { "750", "758" };
		DEFAULT_LEGAL_VALUES[14] = "760";
		DEFAULT_LEGAL_VALUES[15] = "770";
		DEFAULT_LEGAL_VALUES[16] = "771";
		DEFAULT_LEGAL_VALUES[17] = "773";
		DEFAULT_LEGAL_VALUES[18] = "774";
		DEFAULT_LEGAL_VALUES[19] = "776";
		DEFAULT_LEGAL_VALUES[20] = new String[] { "778", "786" };
		DEFAULT_LEGAL_VALUES[21] = "789";
		DEFAULT_LEGAL_VALUES[22] = new String[] { "800", "818" };
		DEFAULT_LEGAL_VALUES[23] = new String[] { "820", "828" };
		DEFAULT_LEGAL_VALUES[24] = new String[] { "830", "832" };
		DEFAULT_LEGAL_VALUES[25] = new String[] { "840", "851" };
		DEFAULT_LEGAL_VALUES[26] = new String[] { "853", "885" };
		DEFAULT_LEGAL_VALUES[27] = "900";
		DEFAULT_LEGAL_VALUES[28] = "901";
		DEFAULT_LEGAL_VALUES[29] = new String[] { "903", "957" };
		DEFAULT_LEGAL_VALUES[30] = new String[] { "960", "989" };
		DEFAULT_LEGAL_VALUES[31] = new String[] { "992", "999" };
		DEFAULT_LEGAL_VALUES[32] = new String[] { "AA1", "AA9" };
		DEFAULT_LEGAL_VALUES[33] = "AAA";
		DEFAULT_LEGAL_VALUES[34] = "AAB";
		DEFAULT_LEGAL_VALUES[35] = new String[] { "AAD", "AAZ" };
		DEFAULT_LEGAL_VALUES[36] = new String[] { "AB1", "AB9" };
		DEFAULT_LEGAL_VALUES[37] = new String[] { "ABA", "ABE" };
		DEFAULT_LEGAL_VALUES[38] = new String[] { "ABG", "ABI" };
		DEFAULT_LEGAL_VALUES[39] = new String[] { "ABK", "ABY" };
		DEFAULT_LEGAL_VALUES[40] = "ACA";
		DEFAULT_LEGAL_VALUES[41] = "ACB";
		DEFAULT_LEGAL_VALUES[42] = "ACK";
		DEFAULT_LEGAL_VALUES[43] = new String[] { "ADB", "ADD" };
		DEFAULT_LEGAL_VALUES[44] = "ADL";
		DEFAULT_LEGAL_VALUES[45] = "ADM";
		DEFAULT_LEGAL_VALUES[46] = "ADR";
		DEFAULT_LEGAL_VALUES[47] = "ARD";
		DEFAULT_LEGAL_VALUES[48] = "CAD";
		DEFAULT_LEGAL_VALUES[49] = "CCR";
		DEFAULT_LEGAL_VALUES[50] = "CDT";
		DEFAULT_LEGAL_VALUES[51] = new String[] { "CEA", "CEF" };
		DEFAULT_LEGAL_VALUES[52] = "CEH";
		DEFAULT_LEGAL_VALUES[53] = new String[] { "CEJ", "CEO" };
		DEFAULT_LEGAL_VALUES[54] = "CLO";
		DEFAULT_LEGAL_VALUES[55] = "CLU";
		DEFAULT_LEGAL_VALUES[56] = "COM";
		DEFAULT_LEGAL_VALUES[57] = "CON";
		DEFAULT_LEGAL_VALUES[58] = "CUR";
		DEFAULT_LEGAL_VALUES[59] = "DDO";
		DEFAULT_LEGAL_VALUES[60] = "DEE";
		DEFAULT_LEGAL_VALUES[61] = "DET";
		DEFAULT_LEGAL_VALUES[62] = "DFF";
		DEFAULT_LEGAL_VALUES[63] = "DFS";
		DEFAULT_LEGAL_VALUES[64] = "DIS";
		DEFAULT_LEGAL_VALUES[65] = "DOI";
		DEFAULT_LEGAL_VALUES[66] = "DSP";
		DEFAULT_LEGAL_VALUES[67] = "ECD";
		DEFAULT_LEGAL_VALUES[68] = "ECF";
		DEFAULT_LEGAL_VALUES[69] = "ECS";
		DEFAULT_LEGAL_VALUES[70] = "ECT";
		DEFAULT_LEGAL_VALUES[71] = "EPP";
		DEFAULT_LEGAL_VALUES[72] = "ESC";
		DEFAULT_LEGAL_VALUES[73] = "ESF";
		DEFAULT_LEGAL_VALUES[74] = "ESS";
		DEFAULT_LEGAL_VALUES[75] = "EST";
		DEFAULT_LEGAL_VALUES[76] = "ETP";
		DEFAULT_LEGAL_VALUES[77] = "EXO";
		DEFAULT_LEGAL_VALUES[78] = "EXP";
		DEFAULT_LEGAL_VALUES[79] = "FFI";
		DEFAULT_LEGAL_VALUES[80] = "GRD";
		DEFAULT_LEGAL_VALUES[81] = "ICF";
		DEFAULT_LEGAL_VALUES[82] = "IDG";
		DEFAULT_LEGAL_VALUES[83] = "III";
		DEFAULT_LEGAL_VALUES[84] = "IMP";
		DEFAULT_LEGAL_VALUES[85] = "INC";
		DEFAULT_LEGAL_VALUES[86] = "INT";
		DEFAULT_LEGAL_VALUES[87] = "KEV";
		DEFAULT_LEGAL_VALUES[88] = "KEW";
		DEFAULT_LEGAL_VALUES[89] = "LAS";
		DEFAULT_LEGAL_VALUES[90] = "LCC";
		DEFAULT_LEGAL_VALUES[91] = "LEA";
		DEFAULT_LEGAL_VALUES[92] = "LEL";
		DEFAULT_LEGAL_VALUES[93] = "LIQ";
		DEFAULT_LEGAL_VALUES[94] = "LLP";
		DEFAULT_LEGAL_VALUES[95] = "LOG";
		DEFAULT_LEGAL_VALUES[96] = "LPC";
		DEFAULT_LEGAL_VALUES[97] = "LSC";
		DEFAULT_LEGAL_VALUES[98] = "LTP";
		DEFAULT_LEGAL_VALUES[99] = "MRR";
		DEFAULT_LEGAL_VALUES[100] = "MSD";
		DEFAULT_LEGAL_VALUES[101] = "NAM";
		DEFAULT_LEGAL_VALUES[102] = "NFD";
		DEFAULT_LEGAL_VALUES[103] = "NRG";
		DEFAULT_LEGAL_VALUES[104] = "NSD";
		DEFAULT_LEGAL_VALUES[105] = "ORG";
		DEFAULT_LEGAL_VALUES[106] = "PBC";
		DEFAULT_LEGAL_VALUES[107] = "PDV";
		DEFAULT_LEGAL_VALUES[108] = "PLS";
		DEFAULT_LEGAL_VALUES[109] = "PPP";
		DEFAULT_LEGAL_VALUES[110] = "PRD";
		DEFAULT_LEGAL_VALUES[111] = "PRR";
		DEFAULT_LEGAL_VALUES[112] = "PTD";
		DEFAULT_LEGAL_VALUES[113] = "RAP";
		DEFAULT_LEGAL_VALUES[114] = "RES";
		DEFAULT_LEGAL_VALUES[115] = "RFD";
		DEFAULT_LEGAL_VALUES[116] = "RFF";
		DEFAULT_LEGAL_VALUES[117] = "RFO";
		DEFAULT_LEGAL_VALUES[118] = "RNT";
		DEFAULT_LEGAL_VALUES[119] = "RRM";
		DEFAULT_LEGAL_VALUES[120] = "RRT";
		DEFAULT_LEGAL_VALUES[121] = "RSD";
		DEFAULT_LEGAL_VALUES[122] = "RSS";
		DEFAULT_LEGAL_VALUES[123] = "RTO";
		DEFAULT_LEGAL_VALUES[124] = "SCV";
		DEFAULT_LEGAL_VALUES[125] = "SDD";
		DEFAULT_LEGAL_VALUES[126] = "STN";
		DEFAULT_LEGAL_VALUES[127] = new String[] { "TSR", "TST" };
		DEFAULT_LEGAL_VALUES[128] = "VAT";
		DEFAULT_LEGAL_VALUES[129] = "VLU";
		DEFAULT_LEGAL_VALUES[130] = new String[] { "W01", "W03" };
		DEFAULT_LEGAL_VALUES[131] = new String[] { "W05", "W0Z" };
		DEFAULT_LEGAL_VALUES[132] = "WAY";
		DEFAULT_LEGAL_VALUES[133] = "YXX";
		DEFAULT_LEGAL_VALUES[134] = "YXY";
		DEFAULT_LEGAL_VALUES[135] = "ZZZ";
		createOverrides();
	}

	public static Object[] getLegalValues(String overrideKey) {
		Object[] currentValues = (Object[]) valueOverrides.get(overrideKey);
		if (currentValues == null) {
			return DEFAULT_LEGAL_VALUES;
		}
		return currentValues;
	}

	private static void createOverrides() {
		Object[] currentValues = null;

		currentValues = new Object[1];
		currentValues[0] = "232";
		valueOverrides.put("18-1", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "232";
		valueOverrides.put("31-1", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "472";
		valueOverrides.put("35-1", currentValues);

		currentValues = new Object[1];
		currentValues[0] = "472";
		valueOverrides.put("22-1", currentValues);
	}

	public static boolean validateValue(String value) {
		return EDIUtils.validateValue(value, DEFAULT_LEGAL_VALUES);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, int segmentOrdinal, int fieldOrdinal) {
		String overrideKey = segmentOrdinal + "-" + fieldOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, String compositeOrdinal, int elementOrdinal) {
		String overrideKey = compositeOrdinal + "-" + elementOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}
}
