package com.webify.shared.edi.model.hipaa835.beans;

import java.util.*;
import com.webify.shared.edi.model.*;

/*
 * AUTOGENERATED FILE - DO NOT EDIT!!!
 */
public class Field569 {

	private static final Object[] DEFAULT_LEGAL_VALUES = new Object[31];
	private static final Map valueOverrides = new HashMap();

	static {
		DEFAULT_LEGAL_VALUES[0] = new String[] { "1", "3" };
		DEFAULT_LEGAL_VALUES[1] = "01";
		DEFAULT_LEGAL_VALUES[2] = "03";
		DEFAULT_LEGAL_VALUES[3] = new String[] { "05", "08" };
		DEFAULT_LEGAL_VALUES[4] = new String[] { "10", "14" };
		DEFAULT_LEGAL_VALUES[5] = "AG";
		DEFAULT_LEGAL_VALUES[6] = "ALC";
		DEFAULT_LEGAL_VALUES[7] = "ANN";
		DEFAULT_LEGAL_VALUES[8] = "AP";
		DEFAULT_LEGAL_VALUES[9] = "BA";
		DEFAULT_LEGAL_VALUES[10] = "CB";
		DEFAULT_LEGAL_VALUES[11] = "CC";
		DEFAULT_LEGAL_VALUES[12] = "CDM";
		DEFAULT_LEGAL_VALUES[13] = "CDS";
		DEFAULT_LEGAL_VALUES[14] = "CM";
		DEFAULT_LEGAL_VALUES[15] = "CRU";
		DEFAULT_LEGAL_VALUES[16] = "DA";
		DEFAULT_LEGAL_VALUES[17] = "DC";
		DEFAULT_LEGAL_VALUES[18] = "EC";
		DEFAULT_LEGAL_VALUES[19] = "EPC";
		DEFAULT_LEGAL_VALUES[20] = "LTD";
		DEFAULT_LEGAL_VALUES[21] = "MUT";
		DEFAULT_LEGAL_VALUES[22] = "PRI";
		DEFAULT_LEGAL_VALUES[23] = "RD";
		DEFAULT_LEGAL_VALUES[24] = "REL";
		DEFAULT_LEGAL_VALUES[25] = "RS";
		DEFAULT_LEGAL_VALUES[26] = "SG";
		DEFAULT_LEGAL_VALUES[27] = "SKA";
		DEFAULT_LEGAL_VALUES[28] = "Z";
		DEFAULT_LEGAL_VALUES[29] = "ZB1";
		DEFAULT_LEGAL_VALUES[30] = "ZB2";
		createOverrides();
	}

	public static Object[] getLegalValues(String overrideKey) {
		Object[] currentValues = (Object[]) valueOverrides.get(overrideKey);
		if (currentValues == null) {
			return DEFAULT_LEGAL_VALUES;
		}
		return currentValues;
	}

	private static void createOverrides() {
		Object[] currentValues = null;

		currentValues = new Object[1];
		currentValues[0] = "DA";
		valueOverrides.put("2-8", currentValues);

		currentValues = new Object[2];
		currentValues[0] = "DA";
		currentValues[1] = "SG";
		valueOverrides.put("2-14", currentValues);
	}

	public static boolean validateValue(String value) {
		return EDIUtils.validateValue(value, DEFAULT_LEGAL_VALUES);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, int segmentOrdinal, int fieldOrdinal) {
		String overrideKey = segmentOrdinal + "-" + fieldOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}

	public static void validateInputValue(EDIInputStream eis, String fieldName, String value, String compositeOrdinal, int elementOrdinal) {
		String overrideKey = compositeOrdinal + "-" + elementOrdinal;
		Object[] values = (Object[]) valueOverrides.get(overrideKey);
		eis.validateInputValue(value, (values == null ? DEFAULT_LEGAL_VALUES : values), fieldName, overrideKey);
	}
}
