package com.webify.shared.edi.model.hipaa835.beans;

import com.webify.shared.edi.model.*;
import java.io.*;
import java.util.*;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/*
 * AUTOGENERATED FILE - DO NOT EDIT!!!
 */
public class SegmentN4_1 implements EDIElement {
	private static final Log log = LogFactory.getLog(SegmentN4_1.class);

	public static final String SEGMENT_NAME = "N4";
	public static final int FIELD_COUNT = 3;

	private int lineNumber = 0;
	public int getLineNumber() { return lineNumber; }
	/** Do NOT use this method - it is not public by choice... */
	public void setLineNumber(int foo) { lineNumber = foo; }

	private int ordinal = 0;
	public int getOrdinal() { return ordinal; }
	void setOrdinal(int ord) { ordinal = ord; }

	// Fields
	private String N401;
	public String getN401() { return N401; }
	public void setN401(String val) { N401 = val; }

	private String N402;
	public String getN402() { return N402; }
	public void setN402(String val) { N402 = val; }

	private String N403;
	public String getN403() { return N403; }
	public void setN403(String val) { N403 = val; }


	public void parse(EDIInputStream eis) throws IOException {
		lineNumber = eis.getCurrentSegmentNumber();
		if (log.isDebugEnabled()) log.debug("Starting segment N4 on line " + lineNumber);
		String[] fields = eis.readSegment(SEGMENT_NAME, FIELD_COUNT);
		N401 = eis.getStringValue(fields, 1, 2, 30, true);
		if (N401 == null || "".equals(fields[1].trim())) {
			eis.addError("Field 'N401' missing");
		}
		N402 = eis.getStringValue(fields, 2, 2, 2, true);
		if (N402 == null || "".equals(fields[2].trim())) {
			eis.addError("Field 'N402' missing");
		}
		N403 = eis.getStringValue(fields, 3, 3, 15, true);
		if (N403 == null || "".equals(fields[3].trim())) {
			eis.addError("Field 'N403' missing");
		}
		validate(eis);
	}

	protected void validate(EDIInputStream eis) {
	}

	public void emit(EDIOutputStream eos) throws IOException {
		eos.startSegment("N4");
		if (N401 == null) {
			eos.addError("Emitting null mandatory field 'N401'");
		}

		eos.writeField(N401);
		if (N402 == null) {
			eos.addError("Emitting null mandatory field 'N402'");
		}

		eos.writeField(N402);
		if (N403 == null) {
			eos.addError("Emitting null mandatory field 'N403'");
		}

		eos.writeField(N403);
		eos.writeNullField();
		eos.writeNullField();
		eos.writeNullField();
		eos.endSegment();
	}

	public EDIElement createCopy() {
		SegmentN4_1 copy = new SegmentN4_1();
		copy.setLineNumber(this.lineNumber);
		copy.N401 = this.N401;
		copy.N402 = this.N402;
		copy.N403 = this.N403;
		return copy;
	}
}
